[project]
name = "mcp-streamablehttp-roaming"
version = "0.1.0"
description = "MCP server demonstrating session roaming across multiple instances using EventStore"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Anthropic, PBC." }]
keywords = ["mcp", "llm", "automation", "streamable", "http", "session", "roaming", "distributed", "redis"]
license = { text = "MIT" }
dependencies = [
    "anyio>=4.5",
    "click>=8.2.0",
    "httpx>=0.27",
    "mcp",
    "redis>=5.0.0",
    "starlette",
    "uvicorn",
]

[project.scripts]
mcp-streamablehttp-roaming = "mcp_simple_streamablehttp_roaming.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["mcp_simple_streamablehttp_roaming"]

[tool.pyright]
include = ["mcp_simple_streamablehttp_roaming"]
venvPath = "."
venv = ".venv"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[tool.ruff]
line-length = 120
target-version = "py310"

[dependency-groups]
dev = ["pyright>=1.1.378", "pytest>=8.3.3", "ruff>=0.6.9"]
