"""Import ratchet for the public type surface.

``mcp.types.__all__`` is pinned exactly: every name exported before the
2026-07-28 protocol work stays exported (zero removals), and new names are
deliberate additions recorded here. The curated top-level ``mcp.__all__`` is
pinned unchanged.
"""

import mcp
import mcp.types

BASELINE_NAMES = frozenset(
    [
        "Annotations",
        "AudioContent",
        "BaseMetadata",
        "BlobResourceContents",
        "CONNECTION_CLOSED",
        "CallToolRequest",
        "CallToolRequestParams",
        "CallToolResult",
        "CancelledNotification",
        "CancelledNotificationParams",
        "ClientCapabilities",
        "ClientNotification",
        "ClientRequest",
        "ClientResult",
        "CompleteRequest",
        "CompleteRequestParams",
        "CompleteResult",
        "Completion",
        "CompletionArgument",
        "CompletionContext",
        "CompletionsCapability",
        "ContentBlock",
        "CreateMessageRequest",
        "CreateMessageRequestParams",
        "CreateMessageResult",
        "CreateMessageResultWithTools",
        "DEFAULT_NEGOTIATED_VERSION",
        "ElicitCompleteNotification",
        "ElicitCompleteNotificationParams",
        "ElicitRequest",
        "ElicitRequestFormParams",
        "ElicitRequestParams",
        "ElicitRequestURLParams",
        "ElicitRequestedSchema",
        "ElicitResult",
        "ElicitationCapability",
        "ElicitationRequiredErrorData",
        "EmbeddedResource",
        "EmptyResult",
        "ErrorData",
        "FormElicitationCapability",
        "GetPromptRequest",
        "GetPromptRequestParams",
        "GetPromptResult",
        "INTERNAL_ERROR",
        "INVALID_PARAMS",
        "INVALID_REQUEST",
        "Icon",
        "IconTheme",
        "ImageContent",
        "Implementation",
        "IncludeContext",
        "InitializeRequest",
        "InitializeRequestParams",
        "InitializeResult",
        "InitializedNotification",
        "JSONRPCError",
        "JSONRPCMessage",
        "JSONRPCNotification",
        "JSONRPCRequest",
        "JSONRPCResponse",
        "LATEST_PROTOCOL_VERSION",
        "ListPromptsRequest",
        "ListPromptsResult",
        "ListResourceTemplatesRequest",
        "ListResourceTemplatesResult",
        "ListResourcesRequest",
        "ListResourcesResult",
        "ListRootsRequest",
        "ListRootsResult",
        "ListToolsRequest",
        "ListToolsResult",
        "LoggingCapability",
        "LoggingLevel",
        "LoggingMessageNotification",
        "LoggingMessageNotificationParams",
        "METHOD_NOT_FOUND",
        "ModelHint",
        "ModelPreferences",
        "Notification",
        "NotificationParams",
        "PARSE_ERROR",
        "PaginatedRequest",
        "PaginatedRequestParams",
        "PaginatedResult",
        "PingRequest",
        "ProgressNotification",
        "ProgressNotificationParams",
        "ProgressToken",
        "Prompt",
        "PromptArgument",
        "PromptListChangedNotification",
        "PromptMessage",
        "PromptReference",
        "PromptsCapability",
        "REQUEST_CANCELLED",
        "REQUEST_TIMEOUT",
        "ReadResourceRequest",
        "ReadResourceRequestParams",
        "ReadResourceResult",
        "Request",
        "RequestId",
        "RequestParams",
        "RequestParamsMeta",
        "Resource",
        "ResourceContents",
        "ResourceLink",
        "ResourceListChangedNotification",
        "ResourceTemplate",
        "ResourceTemplateReference",
        "ResourceUpdatedNotification",
        "ResourceUpdatedNotificationParams",
        "ResourcesCapability",
        "Result",
        "Role",
        "Root",
        "RootsCapability",
        "RootsListChangedNotification",
        "SamplingCapability",
        "SamplingContent",
        "SamplingContextCapability",
        "SamplingMessage",
        "SamplingMessageContentBlock",
        "SamplingToolsCapability",
        "ServerCapabilities",
        "ServerNotification",
        "ServerRequest",
        "ServerResult",
        "SetLevelRequest",
        "SetLevelRequestParams",
        "StopReason",
        "SubscribeRequest",
        "SubscribeRequestParams",
        "TextContent",
        "TextResourceContents",
        "Tool",
        "ToolAnnotations",
        "ToolChoice",
        "ToolListChangedNotification",
        "ToolResultContent",
        "ToolUseContent",
        "ToolsCapability",
        "URL_ELICITATION_REQUIRED",
        "UnsubscribeRequest",
        "UnsubscribeRequestParams",
        "UrlElicitationCapability",
        "client_notification_adapter",
        "client_request_adapter",
        "client_result_adapter",
        "jsonrpc_message_adapter",
        "server_notification_adapter",
        "server_request_adapter",
        "server_result_adapter",
    ]
)
"""Every name ``mcp.types.__all__`` exported before the 2026-07-28 protocol additions."""

ADDED_NAMES = frozenset(
    [
        "CLIENT_CAPABILITIES_META_KEY",
        "CLIENT_INFO_META_KEY",
        "CacheableResult",
        "CancelTaskRequest",
        "CancelTaskRequestParams",
        "CancelTaskResult",
        "CreateTaskResult",
        "DiscoverRequest",
        "DiscoverResult",
        "GetTaskPayloadRequest",
        "GetTaskPayloadRequestParams",
        "GetTaskPayloadResult",
        "GetTaskRequest",
        "GetTaskRequestParams",
        "GetTaskResult",
        "InputRequest",
        "InputRequests",
        "InputRequiredResult",
        "InputResponse",
        "InputResponseRequestParams",
        "InputResponses",
        "JSONRPC_VERSION",
        "LOG_LEVEL_META_KEY",
        "ListTasksRequest",
        "ListTasksResult",
        "MISSING_REQUIRED_CLIENT_CAPABILITY",
        "MissingRequiredClientCapabilityErrorData",
        "PROTOCOL_VERSION_META_KEY",
        "RelatedTaskMetadata",
        "ResultType",
        "SubscriptionFilter",
        "SubscriptionsAcknowledgedNotification",
        "SubscriptionsAcknowledgedNotificationParams",
        "SubscriptionsListenRequest",
        "SubscriptionsListenRequestParams",
        "Task",
        "TaskMetadata",
        "TaskStatus",
        "TaskStatusNotification",
        "TaskStatusNotificationParams",
        "ToolExecution",
        "UNSUPPORTED_PROTOCOL_VERSION",
        "UnsupportedProtocolVersionErrorData",
    ]
)
"""Names deliberately added to ``mcp.types.__all__`` for the 2026-07-28 protocol revision."""

TOP_LEVEL_NAMES = frozenset(
    [
        "CallToolRequest",
        "Client",
        "ClientCapabilities",
        "ClientNotification",
        "ClientRequest",
        "ClientResult",
        "ClientSession",
        "ClientSessionGroup",
        "CompleteRequest",
        "CreateMessageRequest",
        "CreateMessageResult",
        "CreateMessageResultWithTools",
        "ErrorData",
        "GetPromptRequest",
        "GetPromptResult",
        "Implementation",
        "IncludeContext",
        "InitializeRequest",
        "InitializeResult",
        "InitializedNotification",
        "JSONRPCError",
        "JSONRPCRequest",
        "JSONRPCResponse",
        "ListPromptsRequest",
        "ListPromptsResult",
        "ListResourcesRequest",
        "ListResourcesResult",
        "ListToolsResult",
        "LoggingLevel",
        "LoggingMessageNotification",
        "MCPError",
        "Notification",
        "PingRequest",
        "ProgressNotification",
        "PromptsCapability",
        "ReadResourceRequest",
        "ReadResourceResult",
        "Resource",
        "ResourceUpdatedNotification",
        "ResourcesCapability",
        "RootsCapability",
        "SamplingCapability",
        "SamplingContent",
        "SamplingContextCapability",
        "SamplingMessage",
        "SamplingMessageContentBlock",
        "SamplingRole",
        "SamplingToolsCapability",
        "ServerCapabilities",
        "ServerNotification",
        "ServerRequest",
        "ServerResult",
        "ServerSession",
        "SetLevelRequest",
        "StdioServerParameters",
        "StopReason",
        "SubscribeRequest",
        "Tool",
        "ToolChoice",
        "ToolResultContent",
        "ToolUseContent",
        "ToolsCapability",
        "UnsubscribeRequest",
        "UrlElicitationRequiredError",
        "stdio_client",
        "stdio_server",
    ]
)
"""The curated ``mcp.__all__`` surface, which gains nothing from the type work."""


def test_no_baseline_name_removed():
    missing = BASELINE_NAMES - set(mcp.types.__all__)
    assert missing == set(), f"public names removed from mcp.types.__all__: {sorted(missing)}"


def test_exported_surface_is_exactly_baseline_plus_recorded_additions():
    assert set(mcp.types.__all__) == BASELINE_NAMES | ADDED_NAMES


def test_all_has_no_duplicates():
    assert len(mcp.types.__all__) == len(set(mcp.types.__all__))


def test_every_exported_name_is_importable():
    for name in mcp.types.__all__:
        assert hasattr(mcp.types, name), f"mcp.types.__all__ lists {name!r} but the attribute does not exist"


def test_top_level_mcp_surface_unchanged():
    assert set(mcp.__all__) == TOP_LEVEL_NAMES
