pr:
  paths:
    exclude:
      - .idea
      - docs # Exclude changes to documentation

pool:
  vmImage: "ubuntu-22.04"

trigger: none

variables:
  - group: SDLC-SM-HighCode-CI

resources:
  repositories:
    - repository: rd-ai-azure-pipeline-templates
      type: github
      ref: refs/tags/v6.5.1
      name: OutSystems/rd-ai-azure-pipeline-templates
      endpoint: OutSystems

jobs:
  - template: python/packages/new-azure-pipeline-pr.yml@rd-ai-azure-pipeline-templates
    parameters:
      PackageName: "mcp-python-sdk"
      SonarCloudProject: "OutSystems_mcp-python-sdk"
      SonarCloudExclusionList: "tests/**/*,examples/**/*,scripts/*"
      SonarCloudCoverageExclusionList: "tests/**/*,examples/**/*,scripts/*"
      SkipIntegrationTests: true
      PythonVersion: 3.12
      PackageManager: "uv"