listener 1883
allow_anonymous false
use_username_as_clientid true
password_file /tmp/passwords
acl_file /mosquitto/config/mosquitto.acl
persistence false
log_dest stdout
log_type all
max_packet_size 4195328
max_inflight_messages 32
max_queued_messages 256
