# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mcp.v1 import mcp_pb2 as mcp_dot_v1_dot_mcp__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mcp/v1/mcp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class McpServiceStub(object):
    """=============================================================================
    MCP Service Definition
    =============================================================================

    --- Lifecycle ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
                '/mcp.v1.McpService/Initialize',
                request_serializer=mcp_dot_v1_dot_mcp__pb2.InitializeRequest.SerializeToString,
                response_deserializer=mcp_dot_v1_dot_mcp__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/mcp.v1.McpService/Ping',
                request_serializer=mcp_dot_v1_dot_mcp__pb2.PingRequest.SerializeToString,
                response_deserializer=mcp_dot_v1_dot_mcp__pb2.PingResponse.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/mcp.v1.McpService/ListTools',
                request_serializer=mcp_dot_v1_dot_mcp__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=mcp_dot_v1_dot_mcp__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.CallTool = channel.unary_unary(
                '/mcp.v1.McpService/CallTool',
                request_serializer=mcp_dot_v1_dot_mcp__pb2.CallToolRequest.SerializeToString,
                response_deserializer=mcp_dot_v1_dot_mcp__pb2.CallToolResponse.FromString,
                _registered_method=True)
        self.CallToolWithProgress = channel.unary_stream(
                '/mcp.v1.McpService/CallToolWithProgress',
                request_serializer=mcp_dot_v1_dot_mcp__pb2.CallToolWithProgressRequest.SerializeToString,
                response_deserializer=mcp_dot_v1_dot_mcp__pb2.CallToolWithProgressResponse.FromString,
                _registered_method=True)
        self.StreamToolCalls = channel.stream_stream(
                '/mcp.v1.McpService/StreamToolCalls',
                request_serializer=mcp_dot_v1_dot_mcp__pb2.StreamToolCallsRequest.SerializeToString,
                response_deserializer=mcp_dot_v1_dot_mcp__pb2.StreamToolCallsResponse.FromString,
                _registered_method=True)
        self.ListResources = channel.unary_unary(
                '/mcp.v1.McpService/ListResources',
                request_serializer=mcp_dot_v1_dot_mcp__pb2.ListResourcesRequest.SerializeToString,
                response_deserializer=mcp_dot_v1_dot_mcp__pb2.ListResourcesResponse.FromString,
                _registered_method=True)
        self.ListResourceTemplates = channel.unary_unary(
                '/mcp.v1.McpService/ListResourceTemplates',
                request_serializer=mcp_dot_v1_dot_mcp__pb2.ListResourceTemplatesRequest.SerializeToString,
                response_deserializer=mcp_dot_v1_dot_mcp__pb2.ListResourceTemplatesResponse.FromString,
                _registered_method=True)
        self.ReadResource = channel.unary_unary(
                '/mcp.v1.McpService/ReadResource',
                request_serializer=mcp_dot_v1_dot_mcp__pb2.ReadResourceRequest.SerializeToString,
                response_deserializer=mcp_dot_v1_dot_mcp__pb2.ReadResourceResponse.FromString,
                _registered_method=True)
        self.ReadResourceChunked = channel.unary_stream(
                '/mcp.v1.McpService/ReadResourceChunked',
                request_serializer=mcp_dot_v1_dot_mcp__pb2.ReadResourceChunkedRequest.SerializeToString,
                response_deserializer=mcp_dot_v1_dot_mcp__pb2.ReadResourceChunkedResponse.FromString,
                _registered_method=True)
        self.WatchResources = channel.unary_stream(
                '/mcp.v1.McpService/WatchResources',
                request_serializer=mcp_dot_v1_dot_mcp__pb2.WatchResourcesRequest.SerializeToString,
                response_deserializer=mcp_dot_v1_dot_mcp__pb2.WatchResourcesResponse.FromString,
                _registered_method=True)
        self.ListPrompts = channel.unary_unary(
                '/mcp.v1.McpService/ListPrompts',
                request_serializer=mcp_dot_v1_dot_mcp__pb2.ListPromptsRequest.SerializeToString,
                response_deserializer=mcp_dot_v1_dot_mcp__pb2.ListPromptsResponse.FromString,
                _registered_method=True)
        self.GetPrompt = channel.unary_unary(
                '/mcp.v1.McpService/GetPrompt',
                request_serializer=mcp_dot_v1_dot_mcp__pb2.GetPromptRequest.SerializeToString,
                response_deserializer=mcp_dot_v1_dot_mcp__pb2.GetPromptResponse.FromString,
                _registered_method=True)
        self.StreamPromptCompletion = channel.unary_stream(
                '/mcp.v1.McpService/StreamPromptCompletion',
                request_serializer=mcp_dot_v1_dot_mcp__pb2.StreamPromptCompletionRequest.SerializeToString,
                response_deserializer=mcp_dot_v1_dot_mcp__pb2.StreamPromptCompletionResponse.FromString,
                _registered_method=True)
        self.Complete = channel.unary_unary(
                '/mcp.v1.McpService/Complete',
                request_serializer=mcp_dot_v1_dot_mcp__pb2.CompleteRequest.SerializeToString,
                response_deserializer=mcp_dot_v1_dot_mcp__pb2.CompleteResponse.FromString,
                _registered_method=True)
        self.Session = channel.stream_stream(
                '/mcp.v1.McpService/Session',
                request_serializer=mcp_dot_v1_dot_mcp__pb2.SessionRequest.SerializeToString,
                response_deserializer=mcp_dot_v1_dot_mcp__pb2.SessionResponse.FromString,
                _registered_method=True)


class McpServiceServicer(object):
    """=============================================================================
    MCP Service Definition
    =============================================================================

    --- Lifecycle ---
    """

    def Initialize(self, request, context):
        """Initialize the MCP session and negotiate capabilities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Ping for health checks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """--- Tools ---

        List available tools (paginated)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallTool(self, request, context):
        """Call a tool - unary for simple calls
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallToolWithProgress(self, request, context):
        """Call a tool with streaming progress updates
        Server streams progress notifications, final message contains result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamToolCalls(self, request_iterator, context):
        """Stream multiple tool calls - client streams requests, server streams results
        Enables parallel tool execution with results as they complete
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResources(self, request, context):
        """--- Resources ---

        List available resources (paginated)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResourceTemplates(self, request, context):
        """List resource templates (paginated)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadResource(self, request, context):
        """Read a resource - unary for small resources
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadResourceChunked(self, request, context):
        """Read a large resource in chunks - server streams chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchResources(self, request, context):
        """Subscribe to resource changes - server streams notifications
        Replaces polling with push-based updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPrompts(self, request, context):
        """--- Prompts ---

        List available prompts (paginated)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrompt(self, request, context):
        """Get a prompt
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPromptCompletion(self, request, context):
        """Stream prompt completion tokens as they're generated
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Complete(self, request, context):
        """--- Completion ---

        Autocomplete for resource templates or prompts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Session(self, request_iterator, context):
        """--- Bidirectional Session Stream ---

        Full bidirectional stream for complex agent interactions
        Enables any MCP operation over a single persistent connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_McpServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=mcp_dot_v1_dot_mcp__pb2.InitializeRequest.FromString,
                    response_serializer=mcp_dot_v1_dot_mcp__pb2.InitializeResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=mcp_dot_v1_dot_mcp__pb2.PingRequest.FromString,
                    response_serializer=mcp_dot_v1_dot_mcp__pb2.PingResponse.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=mcp_dot_v1_dot_mcp__pb2.ListToolsRequest.FromString,
                    response_serializer=mcp_dot_v1_dot_mcp__pb2.ListToolsResponse.SerializeToString,
            ),
            'CallTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTool,
                    request_deserializer=mcp_dot_v1_dot_mcp__pb2.CallToolRequest.FromString,
                    response_serializer=mcp_dot_v1_dot_mcp__pb2.CallToolResponse.SerializeToString,
            ),
            'CallToolWithProgress': grpc.unary_stream_rpc_method_handler(
                    servicer.CallToolWithProgress,
                    request_deserializer=mcp_dot_v1_dot_mcp__pb2.CallToolWithProgressRequest.FromString,
                    response_serializer=mcp_dot_v1_dot_mcp__pb2.CallToolWithProgressResponse.SerializeToString,
            ),
            'StreamToolCalls': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamToolCalls,
                    request_deserializer=mcp_dot_v1_dot_mcp__pb2.StreamToolCallsRequest.FromString,
                    response_serializer=mcp_dot_v1_dot_mcp__pb2.StreamToolCallsResponse.SerializeToString,
            ),
            'ListResources': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResources,
                    request_deserializer=mcp_dot_v1_dot_mcp__pb2.ListResourcesRequest.FromString,
                    response_serializer=mcp_dot_v1_dot_mcp__pb2.ListResourcesResponse.SerializeToString,
            ),
            'ListResourceTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResourceTemplates,
                    request_deserializer=mcp_dot_v1_dot_mcp__pb2.ListResourceTemplatesRequest.FromString,
                    response_serializer=mcp_dot_v1_dot_mcp__pb2.ListResourceTemplatesResponse.SerializeToString,
            ),
            'ReadResource': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadResource,
                    request_deserializer=mcp_dot_v1_dot_mcp__pb2.ReadResourceRequest.FromString,
                    response_serializer=mcp_dot_v1_dot_mcp__pb2.ReadResourceResponse.SerializeToString,
            ),
            'ReadResourceChunked': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadResourceChunked,
                    request_deserializer=mcp_dot_v1_dot_mcp__pb2.ReadResourceChunkedRequest.FromString,
                    response_serializer=mcp_dot_v1_dot_mcp__pb2.ReadResourceChunkedResponse.SerializeToString,
            ),
            'WatchResources': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchResources,
                    request_deserializer=mcp_dot_v1_dot_mcp__pb2.WatchResourcesRequest.FromString,
                    response_serializer=mcp_dot_v1_dot_mcp__pb2.WatchResourcesResponse.SerializeToString,
            ),
            'ListPrompts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPrompts,
                    request_deserializer=mcp_dot_v1_dot_mcp__pb2.ListPromptsRequest.FromString,
                    response_serializer=mcp_dot_v1_dot_mcp__pb2.ListPromptsResponse.SerializeToString,
            ),
            'GetPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrompt,
                    request_deserializer=mcp_dot_v1_dot_mcp__pb2.GetPromptRequest.FromString,
                    response_serializer=mcp_dot_v1_dot_mcp__pb2.GetPromptResponse.SerializeToString,
            ),
            'StreamPromptCompletion': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPromptCompletion,
                    request_deserializer=mcp_dot_v1_dot_mcp__pb2.StreamPromptCompletionRequest.FromString,
                    response_serializer=mcp_dot_v1_dot_mcp__pb2.StreamPromptCompletionResponse.SerializeToString,
            ),
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=mcp_dot_v1_dot_mcp__pb2.CompleteRequest.FromString,
                    response_serializer=mcp_dot_v1_dot_mcp__pb2.CompleteResponse.SerializeToString,
            ),
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=mcp_dot_v1_dot_mcp__pb2.SessionRequest.FromString,
                    response_serializer=mcp_dot_v1_dot_mcp__pb2.SessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mcp.v1.McpService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mcp.v1.McpService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class McpService(object):
    """=============================================================================
    MCP Service Definition
    =============================================================================

    --- Lifecycle ---
    """

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.McpService/Initialize',
            mcp_dot_v1_dot_mcp__pb2.InitializeRequest.SerializeToString,
            mcp_dot_v1_dot_mcp__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.McpService/Ping',
            mcp_dot_v1_dot_mcp__pb2.PingRequest.SerializeToString,
            mcp_dot_v1_dot_mcp__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.McpService/ListTools',
            mcp_dot_v1_dot_mcp__pb2.ListToolsRequest.SerializeToString,
            mcp_dot_v1_dot_mcp__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.McpService/CallTool',
            mcp_dot_v1_dot_mcp__pb2.CallToolRequest.SerializeToString,
            mcp_dot_v1_dot_mcp__pb2.CallToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallToolWithProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mcp.v1.McpService/CallToolWithProgress',
            mcp_dot_v1_dot_mcp__pb2.CallToolWithProgressRequest.SerializeToString,
            mcp_dot_v1_dot_mcp__pb2.CallToolWithProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamToolCalls(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/mcp.v1.McpService/StreamToolCalls',
            mcp_dot_v1_dot_mcp__pb2.StreamToolCallsRequest.SerializeToString,
            mcp_dot_v1_dot_mcp__pb2.StreamToolCallsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.McpService/ListResources',
            mcp_dot_v1_dot_mcp__pb2.ListResourcesRequest.SerializeToString,
            mcp_dot_v1_dot_mcp__pb2.ListResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListResourceTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.McpService/ListResourceTemplates',
            mcp_dot_v1_dot_mcp__pb2.ListResourceTemplatesRequest.SerializeToString,
            mcp_dot_v1_dot_mcp__pb2.ListResourceTemplatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.McpService/ReadResource',
            mcp_dot_v1_dot_mcp__pb2.ReadResourceRequest.SerializeToString,
            mcp_dot_v1_dot_mcp__pb2.ReadResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadResourceChunked(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mcp.v1.McpService/ReadResourceChunked',
            mcp_dot_v1_dot_mcp__pb2.ReadResourceChunkedRequest.SerializeToString,
            mcp_dot_v1_dot_mcp__pb2.ReadResourceChunkedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mcp.v1.McpService/WatchResources',
            mcp_dot_v1_dot_mcp__pb2.WatchResourcesRequest.SerializeToString,
            mcp_dot_v1_dot_mcp__pb2.WatchResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPrompts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.McpService/ListPrompts',
            mcp_dot_v1_dot_mcp__pb2.ListPromptsRequest.SerializeToString,
            mcp_dot_v1_dot_mcp__pb2.ListPromptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.McpService/GetPrompt',
            mcp_dot_v1_dot_mcp__pb2.GetPromptRequest.SerializeToString,
            mcp_dot_v1_dot_mcp__pb2.GetPromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPromptCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mcp.v1.McpService/StreamPromptCompletion',
            mcp_dot_v1_dot_mcp__pb2.StreamPromptCompletionRequest.SerializeToString,
            mcp_dot_v1_dot_mcp__pb2.StreamPromptCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.McpService/Complete',
            mcp_dot_v1_dot_mcp__pb2.CompleteRequest.SerializeToString,
            mcp_dot_v1_dot_mcp__pb2.CompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/mcp.v1.McpService/Session',
            mcp_dot_v1_dot_mcp__pb2.SessionRequest.SerializeToString,
            mcp_dot_v1_dot_mcp__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
