"""Tests for a language's nav map artefact and its staleness (i18n/nav.py)."""

from dataclasses import replace
from pathlib import Path

import pytest

from i18n.config import ConfigError
from i18n.nav import (
    NavFingerprint,
    NavState,
    NavTranslation,
    classify_nav,
    labels_hash,
    load_nav,
    save_nav,
)

LABELS = ["Get started", "Installation"]


def _state(**overrides: str) -> NavState:
    base = NavState(
        labels_hash=labels_hash(LABELS),
        general_prompt_hash="g",
        instructions_hash="i",
        glossary_hash="l",
        model="model-t",
        translated_at="2026-07-31T00:00:00Z",
    )
    return replace(base, **overrides)


def _fingerprint(**overrides: str) -> NavFingerprint:
    return replace(_state().fingerprint, **overrides)


def test_nav_round_trips_through_the_file_in_nav_order(tmp_path: Path) -> None:
    nav = NavTranslation(labels={"Get started": "はじめに", "Installation": "インストール"}, state=_state())
    path = tmp_path / "nested" / "nav.yml"

    save_nav(path, nav)

    assert load_nav(path) == nav
    text = path.read_text(encoding="utf-8")
    assert text.startswith("# Generated by scripts/docs/i18n")
    assert text.index("Get started") < text.index("Installation") < text.index("labels_hash")


def test_load_nav_missing_file_is_none(tmp_path: Path) -> None:
    assert load_nav(tmp_path / "nav.yml") is None


@pytest.mark.parametrize(
    "document",
    [
        "version: 2\nlabels: {}\nstate: {}\n",
        "version: 1\nlabels: {}\n",
        "version: 1\nlabels: {}\nstate: {}\nextra: 1\n",
        "version: 1\nlabels: {Home: 3}\nstate: {}\n",
        "version: 1\nlabels: {}\nstate: {labels_hash: h}\n",
        "not: [valid: yaml\n",
    ],
)
def test_load_nav_rejects_off_schema_files(tmp_path: Path, document: str) -> None:
    path = tmp_path / "nav.yml"
    path.write_text(document, encoding="utf-8")

    with pytest.raises(ConfigError):
        load_nav(path)


def test_classify_nav_reports_missing_current_and_outdated_with_reasons() -> None:
    nav = NavTranslation(labels={"Get started": "はじめに"}, state=_state())

    assert classify_nav(LABELS, _fingerprint(), None).status == "missing"
    assert classify_nav(LABELS, _fingerprint(), nav).status == "current"
    grown = [*LABELS, "Servers"]
    relabelled = classify_nav(grown, _fingerprint(labels_hash=labels_hash(grown)), nav)
    assert relabelled.status == "outdated" and relabelled.reasons == ("nav labels changed",)
    reworded = classify_nav(LABELS, _fingerprint(glossary_hash="new"), nav)
    assert reworded.status == "outdated" and reworded.reasons == ("glossary changed",)


def test_classify_nav_without_translatable_labels_owes_nothing() -> None:
    assert classify_nav([], _fingerprint(), None).status == "current"
