"""Regenerate the per-version wire-shape surface packages from vendored schemas.

The two surfaces under ``src/mcp/types/v<version>/__init__.py`` are pure
generator output: this script is the only writer. For each entry of
``schema/PINNED.json`` it verifies the vendored ``schema/<version>.json``
against the recorded sha256, runs ``datamodel-code-generator`` (installed via
the ``codegen`` dependency group), applies the post-processing passes
documented on each pass function below, runs ruff, imports the candidate to
audit definition names / field requiredness / ``_meta`` openness, and writes
the result.

Usage (from the repo root)::

    uv run --group codegen python scripts/gen_surface_types.py [--check]

``--check`` regenerates to a temp location and diffs against the committed
files; non-zero exit (with a unified diff) on any drift.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import hashlib
import importlib.util
import json
import re
import shutil
import subprocess
import sys
import tempfile
import textwrap
import typing
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType
from typing import Any

from pydantic import BaseModel

REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMA_DIR = REPO_ROOT / "schema"
PINNED_PATH = SCHEMA_DIR / "PINNED.json"
SRC_TYPES_DIR = REPO_ROOT / "src" / "mcp" / "types"

_SRC_BASE_CLASS = "mcp.types._wire_base.WireModel"

# {@link Target} or {@link Target | label}: emit the label when present.
_JSDOC_LINK_RE = re.compile(r"\{@link\s+(?:[^}|]+?\s*\|\s*)?([^}|]+?)\s*\}")
_GENERATOR_BANNER_RE = re.compile(r"\A# generated by datamodel-codegen:\n(#   filename: [^\n]*\n)?\n*")
_FIELD_ALIAS_RE = re.compile(r"alias=['\"]([^'\"]+)['\"]")

# Wire names whose referenced classes stay extra="allow": schema-open
# pass-through interiors whose unknown keys must survive revalidation.
_OPEN_INTERIOR_FIELD_ALIASES = frozenset({"inputSchema", "outputSchema"})
_OPEN_INTERIOR_COMMENT = "    # Stays open: schema keywords beyond the declared properties ride extra fields.\n"
_SUBSCRIPTION_FILTER_COMMENT = "    # Stays open: filter contents are extensible on the wire.\n"

# Names a relocated cyclic-alias block may reference besides its own members:
# anything else means relocation could break runtime evaluation order.
_RELOCATABLE_NAMES = frozenset(
    {"Annotated", "Any", "Literal", "None", "Optional", "Union"}
    | {"bool", "bytes", "dict", "float", "frozenset", "int", "list", "set", "str", "tuple"}
)

# Per-version module docstrings (the generator emits these verbatim).
SRC_HEADERS: dict[str, str] = {
    "2025-11-25": '''\
"""Internal wire-shape models for protocol 2025-11-25. Not part of the public API.

Generated by `scripts/gen_surface_types.py` from `schema/2025-11-25.json`
@ {spec_commit}. Do not edit; regenerate. Serves inbound validation for every
protocol version through 2025-11-25 (each earlier schema is a strict subset of
this one). Models default to `extra="ignore"`; the few kept open are commented
in place. See `mcp.types._wire_base` and `mcp.types.methods`.
"""
''',
    "2026-07-28": '''\
"""Internal wire-shape models for protocol 2026-07-28. Not part of the public API.

Generated by `scripts/gen_surface_types.py` from `schema/2026-07-28.json`
@ {spec_commit}. Do not edit; regenerate. Schema-exact validators that the
wire-method maps in `mcp.types.methods` point inbound 2026-07-28 validation at.
Models use `extra="ignore"` (unknown keys accepted and dropped) unless commented
otherwise; see `mcp.types._wire_base`.
"""
''',
}

# schema.ts -> schema.json renders TypeScript ``number`` as JSON Schema
# ``integer`` at these sites, so the generator emits ``int``-only annotations
# that reject the floats schema.ts permits. Each entry rewrites one field's
# annotation back to what schema.ts declares.
_NUMBER_PATCH_NOTE = "    # schema.json renders this `number` as integer; widen per schema.ts so floats validate.\n"
FIELD_TYPE_PATCHES: dict[str, list[tuple[str, str, str]]] = {
    "2025-11-25": [
        ("ElicitResult", "content", "dict[str, list[str] | str | int | float | bool] | None"),
        ("NumberSchema", "default", "int | float | None"),
        ("NumberSchema", "maximum", "int | float | None"),
        ("NumberSchema", "minimum", "int | float | None"),
    ],
    "2026-07-28": [
        ("ElicitResult", "content", "dict[str, list[str] | str | int | float | bool] | None"),
    ],
}

# Same defect for the recursive JSONValue alias (2026 only): schema.json's
# primitive arm is string|integer|boolean where schema.ts has all six JSON
# types. Rewrites the TypeAliasType value string.
ALIAS_TYPE_PATCHES: dict[str, dict[str, str]] = {
    "2026-07-28": {"JSONValue": "JSONObject | list[JSONValue] | str | int | float | bool | None"},
}

# Hand-written union aliases the wire-method maps reference by value; the
# schema has no named definition for "everything tools/call may return", so the
# generator emits the union inline on the response model and these name it.
EPILOGUES: dict[str, str] = {
    "2026-07-28": '''\
AnyCallToolResult: TypeAlias = CallToolResult | InputRequiredResult
"""Named alias for `CallToolResultResponse.result` so the wire-method maps can reference it as a value."""

AnyGetPromptResult: TypeAlias = GetPromptResult | InputRequiredResult
"""Everything a `prompts/get` response's `result` may be at this version."""

AnyReadResourceResult: TypeAlias = ReadResourceResult | InputRequiredResult
"""Everything a `resources/read` response's `result` may be at this version."""
''',
}


class PipelineError(Exception):
    """A stage of the pipeline failed; the message says which and why."""


@dataclass
class Entry:
    """One PINNED.json entry."""

    protocol_version: str
    source_path_in_spec_repo: str
    spec_commit: str
    sha256: str

    @property
    def module(self) -> str:
        return "v" + self.protocol_version.replace("-", "_")

    @property
    def schema_file(self) -> Path:
        return SCHEMA_DIR / f"{self.protocol_version}.json"

    @property
    def target(self) -> Path:
        return SRC_TYPES_DIR / self.module / "__init__.py"


def load_pinned() -> list[Entry]:
    """Read schema/PINNED.json and verify each vendored file's sha256."""
    with PINNED_PATH.open() as f:
        raw: list[dict[str, str]] = json.load(f)
    entries = [Entry(**item) for item in raw]
    for entry in entries:
        if not entry.schema_file.is_file():
            raise PipelineError(f"{entry.protocol_version}: vendored schema {entry.schema_file} is missing")
        actual = hashlib.sha256(entry.schema_file.read_bytes()).hexdigest()
        if actual != entry.sha256:
            raise PipelineError(
                f"{entry.protocol_version}: sha256 mismatch for {entry.schema_file.name} "
                f"(PINNED.json={entry.sha256}, on disk={actual})"
            )
    return entries


def run_generator(schema_path: Path, output_path: Path) -> None:
    """Run datamodel-code-generator (from the ``codegen`` dependency group)."""
    exe = shutil.which("datamodel-codegen")
    cmd = [exe] if exe else ["uv", "run", "--group", "codegen", "datamodel-codegen"]
    result = subprocess.run(
        [
            *cmd,
            "--input",
            str(schema_path),
            "--input-file-type",
            "jsonschema",
            "--output",
            str(output_path),
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--target-python-version",
            "3.10",
            "--base-class",
            _SRC_BASE_CLASS,
            "--snake-case-field",
            "--remove-special-field-name-prefix",
            "--use-annotated",
            "--use-field-description",
            "--use-schema-description",
            "--enum-field-as-literal",
            "all",
            "--use-union-operator",
            "--use-double-quotes",
            "--extra-fields",
            "allow",
            "--disable-timestamp",
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0 or not output_path.is_file():
        raise PipelineError(f"datamodel-codegen failed:\n{result.stderr.strip()}")


def _end_lineno(node: ast.stmt) -> int:
    """End line of a statement (ast fills end_lineno for parsed code)."""
    end = node.end_lineno
    if end is None:
        raise PipelineError(f"ast node at line {node.lineno} has no end_lineno")
    return end


def _collect_rootmodel_aliases(tree: ast.Module) -> dict[str, tuple[ast.ClassDef, str]]:
    """Map class name -> (node, unparsed RootModel type argument) for RootModel subclasses."""
    aliases: dict[str, tuple[ast.ClassDef, str]] = {}
    for node in tree.body:
        if not isinstance(node, ast.ClassDef) or len(node.bases) != 1:
            continue
        base = node.bases[0]
        if isinstance(base, ast.Subscript) and isinstance(base.value, ast.Name) and base.value.id == "RootModel":
            aliases[node.name] = (node, ast.unparse(base.slice))
    return aliases


def _find_recursive_aliases(aliases: dict[str, tuple[ast.ClassDef, str]]) -> set[str]:
    """Names of alias classes that participate in a reference cycle."""

    def refs(type_expr: str) -> set[str]:
        bare = type_expr.replace("'", " ").replace('"', " ")
        return {name for name in aliases if re.search(rf"\b{name}\b", bare)}

    cyclic: set[str] = set()
    for name, (_, type_expr) in aliases.items():
        seen: set[str] = set()
        stack = list(refs(type_expr))
        while stack:
            current = stack.pop()
            if current == name:
                cyclic.add(name)
                break
            if current in seen or current not in aliases:
                continue
            seen.add(current)
            stack.extend(refs(aliases[current][1]))
    return cyclic


def _alias_statement(name: str, node: ast.ClassDef, alias_type: str, *, string_form: bool) -> str:
    """One converted alias definition (docstring preserved as a trailing string)."""
    if string_form:
        value = alias_type.replace("'", "").replace('"', "")
        text = f'{name} = TypeAliasType("{name}", "{value}")\n'
    else:
        text = f'{name} = TypeAliasType("{name}", {alias_type})\n'
    docstring = ast.get_docstring(node)
    if docstring and '"""' not in docstring:
        text += '"""' + docstring + '"""\n'
    return text


def _emit_cyclic_block(
    ordered: list[str], aliases: dict[str, tuple[ast.ClassDef, str]], alias_patches: dict[str, str]
) -> str:
    """Emit a group of mutually recursive aliases in the one form pyright accepts.

    Self-referencing members go first as a whole-string value (lazily parsed),
    the rest follow in expression form so quoted references point backwards;
    the caller relocates the whole block to just after the imports. Any
    ``alias_patches`` entry overrides the generator's value (always emitted
    string-form, with a leading comment).
    """

    def has_self_ref(name: str) -> bool:
        bare = aliases[name][1].replace("'", " ").replace('"', " ")
        return re.search(rf"\b{name}\b", bare) is not None

    string_members = [n for n in ordered if has_self_ref(n)]
    expr_members = [n for n in ordered if not has_self_ref(n)]
    parts: list[str] = []
    for name in [*string_members, *expr_members]:
        node, generated = aliases[name]
        if name in alias_patches:
            parts.append(
                "# schema.json renders the primitive arm without float/null; widen per schema.ts.\n"
                + _alias_statement(name, node, alias_patches[name], string_form=True)
            )
        else:
            parts.append(_alias_statement(name, node, generated, string_form=name in string_members))
    return "\n\n".join(parts)


def _group_is_self_contained(cyclic: set[str], aliases: dict[str, tuple[ast.ClassDef, str]]) -> bool:
    """True if the cyclic group references only its own members and builtins."""
    allowed = cyclic | _RELOCATABLE_NAMES
    for name in cyclic:
        bare = aliases[name][1].replace("'", " ").replace('"', " ")
        identifiers = set(re.findall(r"[A-Za-z_][A-Za-z0-9_]*", bare))
        if not identifiers <= allowed:
            return False
    return True


def postprocess(source: str, alias_patches: dict[str, str]) -> tuple[str, list[str]]:
    """Convert RootModel wrappers to aliases and clean up generator artifacts.

    Returns the rewritten source and the sorted recursive-alias names (for the
    follow-up assertion that the relocated block survived).
    """
    source = _GENERATOR_BANNER_RE.sub("", source)
    tree = ast.parse(source)
    lines = source.splitlines(keepends=True)

    aliases = _collect_rootmodel_aliases(tree)
    cyclic = _find_recursive_aliases(aliases)

    converted = 0
    cyclic_in_order = [name for name in aliases if name in cyclic]
    relocate = bool(cyclic) and _group_is_self_contained(cyclic, aliases)
    replacements: list[tuple[int, int, str]] = []  # 1-based inclusive line ranges
    for name, (node, alias_type) in aliases.items():
        if name == "Model" and alias_type == "Any":
            # The generator's synthetic artifact for the schema's empty root.
            replacements.append((node.lineno, _end_lineno(node), ""))
            continue
        if name in cyclic:
            # The whole group is emitted as one block (see _emit_cyclic_block):
            # relocated to just after the imports when self-contained, else at
            # the first member's position.
            if relocate or name != cyclic_in_order[0]:
                new = ""
            else:
                new = _emit_cyclic_block(cyclic_in_order, aliases, alias_patches)
        else:
            new = f"{name}: TypeAlias = {alias_type}\n"
            docstring = ast.get_docstring(node)
            if docstring and '"""' not in docstring:
                new += '"""' + docstring + '"""\n'
        replacements.append((node.lineno, _end_lineno(node), new))
        converted += 1
    if relocate:
        last_import_end = max(_end_lineno(node) for node in tree.body if isinstance(node, ast.Import | ast.ImportFrom))
        block = _emit_cyclic_block(cyclic_in_order, aliases, alias_patches)
        # Pure insertion AFTER the last import line (start = end + 1), never a
        # replacement of it: the import line itself may carry its own
        # replacement (dropping RootModel), and two edits to one line range
        # silently clobber each other.
        replacements.append((last_import_end + 1, last_import_end, "\n" + block))

    # Import fixes, on the same parsed tree: drop RootModel from the pydantic
    # import, add TypeAlias / TypeAliasType where conversions need them.
    need_type_alias = converted > len(cyclic)
    need_type_alias_type = bool(cyclic)
    typing_handled = False
    for node in tree.body:
        if not isinstance(node, ast.ImportFrom):
            continue
        if node.module == "pydantic":
            names = [alias for alias in node.names if alias.name != "RootModel"]
            text = ast.unparse(ast.ImportFrom(module="pydantic", names=names, level=0)) + "\n" if names else ""
            replacements.append((node.lineno, _end_lineno(node), text))
        elif node.module == "typing":
            typing_handled = True
            names = list(node.names)
            if need_type_alias and not any(alias.name == "TypeAlias" for alias in names):
                names.append(ast.alias(name="TypeAlias"))
            text = ast.unparse(ast.ImportFrom(module="typing", names=names, level=0)) + "\n"
            if need_type_alias_type:
                text += "from typing_extensions import TypeAliasType\n"
            replacements.append((node.lineno, _end_lineno(node), text))
    if not typing_handled and (need_type_alias or need_type_alias_type):
        extra = "from typing import TypeAlias\n" if need_type_alias else ""
        if need_type_alias_type:
            extra += "from typing_extensions import TypeAliasType\n"
        for node in tree.body:
            if isinstance(node, ast.ImportFrom) and node.module == "__future__":
                replacements.append((node.lineno, _end_lineno(node), lines[node.lineno - 1] + extra))
                break

    for start, end, new in sorted(replacements, reverse=True):
        lines[start - 1 : end] = [new]
    source = "".join(lines)

    # model_rebuild() is only valid on classes; drop calls for converted names.
    for name in [*aliases, "Model"]:
        source = re.sub(rf"^{name}\.model_rebuild\(\)\n", "", source, flags=re.MULTILINE)

    source = _JSDOC_LINK_RE.sub(r"\1", source)
    return source, sorted(cyclic)


def assert_alias_blocks_present(source: str, recursive: list[str]) -> None:
    """Assert every recursive alias survived post-processing into the output."""
    for name in recursive:
        if not re.search(rf'^{name} = TypeAliasType\("{name}"', source, flags=re.MULTILINE):
            raise PipelineError(f"recursive alias {name!r} is missing from the post-processed output")


def downgrade_value_transforms(source: str) -> str:
    """Replace value-transforming pydantic types with plain ``str``.

    URL normalization and base64 re-encoding change bytes on a validate ->
    re-dump round trip; the wire models must reproduce input bytes exactly.
    """
    source = re.sub(r"\b(AnyUrl|FileUrl|Base64Str)\b", "str", source)
    match = re.search(r"^from pydantic import (.+)$", source, flags=re.MULTILINE)
    if match:
        names = [n.strip() for n in match.group(1).split(",")]
        kept = [n for n in names if n != "str"]
        source = source.replace(match.group(0), f"from pydantic import {', '.join(kept)}")
    return source


def widen_structured_content(source: str) -> str:
    """Widen typed ``structuredContent`` fields to ``Any`` (2026-07-28 only).

    The 2026-07-28 schema types the field as any JSON value; the 2025-11-25
    surface keeps the schema's ``dict[str, Any]`` so this pass is gated.
    """
    tree = ast.parse(source)
    lines = source.splitlines(keepends=True)
    statements = [
        stmt
        for node in tree.body
        if isinstance(node, ast.ClassDef)
        for stmt in node.body
        if isinstance(stmt, ast.AnnAssign)
        and isinstance(stmt.target, ast.Name)
        and stmt.target.id == "structured_content"
    ]
    for stmt in sorted(statements, key=lambda s: s.lineno, reverse=True):
        start, end = stmt.lineno, _end_lineno(stmt)
        segment = "".join(lines[start - 1 : end])
        lines[start - 1 : end] = [segment.replace("dict[str, Any]", "Any")]
    return "".join(lines)


def _class_field_aliases(node: ast.ClassDef) -> list[tuple[ast.AnnAssign, str, str]]:
    """(statement, field name, wire alias) for every annotated field of a class."""
    out: list[tuple[ast.AnnAssign, str, str]] = []
    for stmt in node.body:
        if not isinstance(stmt, ast.AnnAssign) or not isinstance(stmt.target, ast.Name):
            continue
        annotation_text = ast.unparse(stmt.annotation)
        alias_match = _FIELD_ALIAS_RE.search(annotation_text)
        alias = alias_match.group(1) if alias_match else stmt.target.id
        out.append((stmt, stmt.target.id, alias))
    return out


def apply_field_type_patches(source: str, patches: list[tuple[str, str, str]]) -> str:
    """Rewrite the annotations listed in ``FIELD_TYPE_PATCHES`` for one version.

    Each patch names a (class, field) and the replacement annotation; the
    generator's annotation is found via AST and the new one is spliced into the
    same line range with a one-line provenance comment above it.
    """
    if not patches:
        return source
    tree = ast.parse(source)
    lines = source.splitlines(keepends=True)
    classes: dict[str, ast.ClassDef] = {n.name: n for n in tree.body if isinstance(n, ast.ClassDef)}
    replacements: list[tuple[int, int, str]] = []
    for cls_name, field_name, new_annotation in patches:
        node = classes.get(cls_name)
        if node is None:
            raise PipelineError(f"field-type patch targets missing class {cls_name}")
        stmt = next(
            (s for s, name, _ in _class_field_aliases(node) if name == field_name),
            None,
        )
        if stmt is None:
            raise PipelineError(f"field-type patch targets missing field {cls_name}.{field_name}")
        default = f" = {ast.unparse(stmt.value)}" if stmt.value is not None else ""
        new = f"{_NUMBER_PATCH_NOTE}    {field_name}: {new_annotation}{default}\n"
        replacements.append((stmt.lineno, _end_lineno(stmt), new))
    for start, end, new in sorted(replacements, reverse=True):
        lines[start - 1 : end] = [new]
    return "".join(lines)


def flatten_inheritance(source: str) -> str:
    """Flatten classes that subclass other generated classes.

    The generator emits subclassing where one definition narrows another;
    pyright's dataclass-transform rules reject the narrowed overrides, and the
    committed packages carry no suppressions. Flattening re-declares inherited
    fields directly: base fields in base order, overrides in place, own fields
    appended.
    """
    tree = ast.parse(source)
    lines = source.splitlines(keepends=True)
    classes: dict[str, ast.ClassDef] = {n.name: n for n in tree.body if isinstance(n, ast.ClassDef)}

    def field_segments(node: ast.ClassDef) -> list[tuple[str, str]]:
        segments: list[tuple[str, str]] = []
        body = list(node.body)
        for index, stmt in enumerate(body):
            if not isinstance(stmt, ast.AnnAssign) or not isinstance(stmt.target, ast.Name):
                continue
            end = _end_lineno(stmt)
            if index + 1 < len(body):
                nxt = body[index + 1]
                if isinstance(nxt, ast.Expr) and isinstance(nxt.value, ast.Constant):
                    if isinstance(nxt.value.value, str):
                        end = _end_lineno(nxt)
            segments.append((stmt.target.id, "".join(lines[stmt.lineno - 1 : end])))
        return segments

    resolved: dict[str, list[tuple[str, str]]] = {}

    def resolve(name: str) -> list[tuple[str, str]]:
        if name in resolved:
            return resolved[name]
        node = classes[name]
        base_names = [b.id for b in node.bases if isinstance(b, ast.Name) and b.id in classes]
        merged: list[tuple[str, str]] = []
        for base in base_names:
            for field_name, text in resolve(base):
                if field_name not in {n for n, _ in merged}:
                    merged.append((field_name, text))
        for field_name, text in field_segments(node):
            existing = [i for i, (n, _) in enumerate(merged) if n == field_name]
            if existing:
                merged[existing[0]] = (field_name, text)
            else:
                merged.append((field_name, text))
        resolved[name] = merged
        return merged

    replacements: list[tuple[int, int, str]] = []
    for name, node in classes.items():
        generated_bases = [b.id for b in node.bases if isinstance(b, ast.Name) and b.id in classes]
        if not generated_bases:
            continue
        parts: list[str] = [f"class {name}(WireModel):\n"]
        if ast.get_docstring(node) is not None:
            stmt = node.body[0]
            parts.append("".join(lines[stmt.lineno - 1 : _end_lineno(stmt)]))
        parts.extend(
            "".join(lines[stmt.lineno - 1 : _end_lineno(stmt)])
            for stmt in node.body
            if isinstance(stmt, ast.Assign)
            and any(isinstance(t, ast.Name) and t.id == "model_config" for t in stmt.targets)
        )
        parts.extend(text for _, text in resolve(name))
        replacements.append((node.lineno, _end_lineno(node), "".join(parts)))

    for start, end, new in sorted(replacements, reverse=True):
        lines[start - 1 : end] = [new]
    return "".join(lines)


def rebase_meta_carriers(source: str) -> tuple[str, list[str]]:
    """Rebase classes referenced from ``_meta`` fields onto ``OpenWireModel``."""
    tree = ast.parse(source)
    classes: dict[str, ast.ClassDef] = {n.name: n for n in tree.body if isinstance(n, ast.ClassDef)}
    carriers: set[str] = set()
    for node in classes.values():
        for stmt, _, alias in _class_field_aliases(node):
            if alias != "_meta":
                continue
            annotation_text = ast.unparse(stmt.annotation)
            carriers.update(name for name in classes if re.search(rf"\b{name}\b", annotation_text))
    for name in sorted(carriers):
        source = re.sub(
            rf"^class {name}\(WireModel\):$",
            f"class {name}(OpenWireModel):",
            source,
            flags=re.MULTILINE,
        )
    return source, sorted(carriers)


def apply_extra_policy(source: str, carriers: list[str]) -> str:
    """Force ``extra="ignore"`` everywhere except the enumerated open classes."""
    tree = ast.parse(source)
    lines = source.splitlines(keepends=True)
    classes: dict[str, ast.ClassDef] = {n.name: n for n in tree.body if isinstance(n, ast.ClassDef)}

    keep_allow: set[str] = set()
    for node in classes.values():
        for stmt, _, alias in _class_field_aliases(node):
            if alias in _OPEN_INTERIOR_FIELD_ALIASES:
                annotation_text = ast.unparse(stmt.annotation)
                keep_allow.update(name for name in classes if re.search(rf"\b{name}\b", annotation_text))
    if "SubscriptionFilter" in classes:
        keep_allow.add("SubscriptionFilter")

    replacements: list[tuple[int, int, str]] = []
    for name, node in classes.items():
        config_stmt = next(
            (
                stmt
                for stmt in node.body
                if isinstance(stmt, ast.Assign)
                and any(isinstance(t, ast.Name) and t.id == "model_config" for t in stmt.targets)
            ),
            None,
        )
        if config_stmt is None:
            continue
        value = config_stmt.value
        is_plain_allow = (
            isinstance(value, ast.Call)
            and isinstance(value.func, ast.Name)
            and value.func.id == "ConfigDict"
            and len(value.keywords) == 1
            and value.keywords[0].arg == "extra"
            and isinstance(value.keywords[0].value, ast.Constant)
            and value.keywords[0].value.value == "allow"
        )
        if not is_plain_allow:
            raise PipelineError(f"unexpected model_config on {name}: {ast.unparse(config_stmt)}")
        if name in keep_allow and name not in carriers:
            comment = _SUBSCRIPTION_FILTER_COMMENT if name == "SubscriptionFilter" else _OPEN_INTERIOR_COMMENT
            replacements.append((config_stmt.lineno, config_stmt.lineno - 1, comment))
            continue
        remaining = [stmt for stmt in node.body if stmt is not config_stmt]
        new = "" if remaining else "    pass\n"
        replacements.append((config_stmt.lineno, _end_lineno(config_stmt), new))

    for start, end, new in sorted(replacements, reverse=True):
        lines[start - 1 : end] = [new]
    return "".join(lines)


def deterministic_synthetic_names(source: str) -> str:
    """Rename counter-based synthetic classes after their single owner."""
    tree = ast.parse(source)
    classes: dict[str, ast.ClassDef] = {n.name: n for n in tree.body if isinstance(n, ast.ClassDef)}
    synthetic = {name for name in classes if re.fullmatch(r"(?:Params|Meta)\d*", name)}
    references: dict[str, list[tuple[str, str]]] = {name: [] for name in synthetic}
    for node in classes.values():
        for stmt, field_name, _ in _class_field_aliases(node):
            annotation_text = ast.unparse(stmt.annotation)
            for name in synthetic:
                if re.search(rf"\b{name}\b", annotation_text):
                    references[name].append((node.name, field_name))

    renames: dict[str, str] = {}
    taken = set(classes)
    for name in sorted(synthetic):
        refs = references[name]
        if len(refs) != 1:
            continue
        owner, field_name = refs[0]
        suffix = {"params": "Params", "meta": "Meta"}.get(field_name)
        if suffix is None:
            continue
        target = f"{owner}{suffix}"
        if target in taken:
            continue
        renames[name] = target
        taken.add(target)

    if renames:
        pattern = re.compile(r"\b(" + "|".join(sorted(renames, key=len, reverse=True)) + r")\b")
        source = pattern.sub(lambda m: renames[m.group(1)], source)
    return source


def _join_class_docstring_summaries(source: str) -> str:
    """Move each class docstring summary onto the opening quote line.

    The D212 fix, applied first so the long-line wrapping below stays in
    charge of the resulting line length.
    """
    tree = ast.parse(source)
    lines = source.splitlines(keepends=True)
    for node in tree.body:
        if not isinstance(node, ast.ClassDef) or ast.get_docstring(node) is None:
            continue
        stmt = node.body[0]
        first = lines[stmt.lineno - 1]
        if first.strip() != '"""' or _end_lineno(stmt) == stmt.lineno:
            continue
        summary = lines[stmt.lineno].strip()
        single_content = _end_lineno(stmt) == stmt.lineno + 2
        indent = first[: len(first) - len(first.lstrip())]
        if single_content:
            if len(indent) + len(summary) + 6 <= 120:
                lines[stmt.lineno - 1] = f'{indent}"""{summary}"""\n'
                lines[stmt.lineno] = ""
                lines[stmt.lineno + 1] = ""
            else:
                wrapped = textwrap.wrap(
                    summary,
                    width=117,
                    initial_indent=indent + '"""',
                    subsequent_indent=indent,
                    break_long_words=False,
                    break_on_hyphens=False,
                )
                lines[stmt.lineno - 1] = "".join(part + "\n" for part in wrapped)
                lines[stmt.lineno] = ""
            continue
        lines[stmt.lineno - 1] = first.rstrip("\n") + summary + "\n"
        lines[stmt.lineno] = ""
    return "".join(lines)


def wrap_docstrings(source: str) -> str:
    """Wrap docstring lines to the repo line length (no per-file E501 exemption)."""
    source = _join_class_docstring_summaries(source)
    out: list[str] = []
    in_docstring = False
    for line in source.splitlines(keepends=True):
        quotes = line.count('"""')
        long = len(line.rstrip("\n")) > 120
        indent = line[: len(line) - len(line.lstrip())]
        if not in_docstring:
            if quotes == 1:
                in_docstring = True
                if long:
                    out.extend(
                        part + "\n"
                        for part in textwrap.wrap(
                            line.strip().removeprefix('"""'),
                            width=120,
                            initial_indent=indent + '"""',
                            subsequent_indent=indent,
                            break_long_words=False,
                            break_on_hyphens=False,
                        )
                    )
                    continue
            out.append(line)
            continue
        if quotes:
            in_docstring = False
            out.append(line)
            continue
        if not long:
            out.append(line)
            continue
        out.extend(
            part + "\n"
            for part in textwrap.wrap(
                line.strip(),
                width=120,
                initial_indent=indent,
                subsequent_indent=indent,
                break_long_words=False,
                break_on_hyphens=False,
            )
        )
    return "".join(out)


def assert_only_wire_bases(source: str) -> None:
    """Assert every class in the emitted package sits on one of the two bases."""
    tree = ast.parse(source)
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        base_names = [ast.unparse(b) for b in node.bases]
        if base_names not in (["WireModel"], ["OpenWireModel"]):
            raise PipelineError(f"class {node.name} has unexpected bases {base_names} after the src passes")


def run_ruff(path: Path) -> None:
    """ruff check --fix + format with the repo config; abort on any residual finding."""
    common = ["uv", "run", "--frozen", "ruff"]
    fix = subprocess.run(
        [*common, "check", "--no-cache", "--fix", "--exit-zero", str(path)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if fix.returncode != 0:
        raise PipelineError(f"ruff check --fix failed:\n{fix.stderr.strip()}")
    fmt = subprocess.run([*common, "format", "--no-cache", str(path)], cwd=REPO_ROOT, capture_output=True, text=True)
    if fmt.returncode != 0:
        raise PipelineError(f"ruff format failed:\n{fmt.stderr.strip()}")
    report = subprocess.run(
        [*common, "check", "--no-cache", "--output-format", "json", "--exit-zero", str(path)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if report.returncode != 0:
        raise PipelineError(f"ruff check (report) failed:\n{report.stderr.strip()}")
    findings: list[dict[str, Any]] = json.loads(report.stdout)
    if findings:
        details = "\n".join(
            f"  {f.get('code')}: {f.get('message')} (line {f.get('location', {}).get('row')})" for f in findings
        )
        raise PipelineError(f"ruff residual findings in {path.name}:\n{details}")


def schema_defs(schema: dict[str, Any]) -> dict[str, Any]:
    """The definitions table of a schema ($defs in 2020-12, definitions in draft-07)."""
    defs = schema.get("$defs") or schema.get("definitions")
    if not defs:
        raise PipelineError("schema has no $defs/definitions table")
    return defs


def import_candidate(path: Path, module: str) -> ModuleType:
    """Import a staged candidate module under a private name."""
    name = f"_candidate_{module}"
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise PipelineError(f"cannot load candidate module from {path}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def audit_candidate(mod: ModuleType, schema: dict[str, Any], entry: Entry) -> None:
    """Def-name + alias + requiredness audit; raises on any failure."""
    problems: list[str] = []
    for def_name, def_schema in schema_defs(schema).items():
        obj = getattr(mod, def_name, None)
        if obj is None:
            problems.append(f"def {def_name!r} does not resolve to a module attribute")
            continue
        if not (isinstance(obj, type) and issubclass(obj, BaseModel)):
            continue
        properties: dict[str, Any] = def_schema.get("properties", {})
        required: list[str] = def_schema.get("required", [])
        fields_by_wire_name = {
            (info.serialization_alias or info.alias or field_name): info
            for field_name, info in obj.model_fields.items()
        }
        for prop_name in properties:
            info = fields_by_wire_name.get(prop_name)
            if info is None:
                problems.append(f"{def_name}: no field with wire name {prop_name!r}")
                continue
            if info.is_required() != (prop_name in required):
                problems.append(
                    f"{def_name}.{prop_name}: requiredness mismatch "
                    f"(model={info.is_required()}, schema={prop_name in required})"
                )
    if problems:
        raise PipelineError(f"{entry.protocol_version}: audit failed:\n" + "\n".join(f"  - {p}" for p in problems))


def _annotation_models(annotation: Any) -> list[type[BaseModel]]:
    """Model classes appearing anywhere in an annotation."""
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return [annotation]
    found: list[type[BaseModel]] = []
    for arg in typing.get_args(annotation):
        found.extend(_annotation_models(arg))
    return found


def audit_meta_carriers(mod: ModuleType, entry: Entry) -> None:
    """Assert every ``_meta`` field is open: a dict, or an extra='allow' model."""
    problems: list[str] = []
    for name in dir(mod):
        obj = getattr(mod, name)
        if not (isinstance(obj, type) and issubclass(obj, BaseModel)):
            continue
        for field_name, info in obj.model_fields.items():
            if (info.serialization_alias or info.alias or field_name) != "_meta":
                continue
            problems.extend(
                f"{name}._meta references {referenced.__name__}, which is not extra='allow'"
                for referenced in _annotation_models(info.annotation)
                if referenced.model_config.get("extra") != "allow"
            )
    if problems:
        raise PipelineError(
            f"{entry.protocol_version}: _meta carrier audit failed:\n" + "\n".join(f"  - {p}" for p in problems)
        )


def build_candidate(entry: Entry) -> str:
    """Full pipeline for one entry; returns the formatted, audited source text."""
    schema: dict[str, Any] = json.loads(entry.schema_file.read_text())

    with tempfile.TemporaryDirectory() as tmp:
        raw_file = Path(tmp) / "raw.py"
        run_generator(entry.schema_file, raw_file)
        source, recursive = postprocess(raw_file.read_text(), ALIAS_TYPE_PATCHES.get(entry.protocol_version, {}))
    assert_alias_blocks_present(source, recursive)

    source = downgrade_value_transforms(source)
    if entry.protocol_version == "2026-07-28":
        source = widen_structured_content(source)
    source = flatten_inheritance(source)
    source, carriers = rebase_meta_carriers(source)
    if carriers:
        source = source.replace(
            "from mcp.types._wire_base import WireModel",
            "from mcp.types._wire_base import OpenWireModel, WireModel",
        )
    source = apply_extra_policy(source, carriers)
    source = deterministic_synthetic_names(source)
    source = apply_field_type_patches(source, FIELD_TYPE_PATCHES.get(entry.protocol_version, []))
    source = wrap_docstrings(source)

    epilogue = EPILOGUES.get(entry.protocol_version, "")
    if epilogue:
        # Before model_rebuild(), not after: pyright's evaluation order for the
        # recursive TypeAliasType block at the top is sensitive to where the
        # last cross-module-referenced symbol sits.
        match = re.search(r"^\w+\.model_rebuild\(\)$", source, flags=re.MULTILINE)
        cut = match.start() if match else len(source)
        source = source[:cut] + epilogue + "\n\n" + source[cut:]
    header = SRC_HEADERS[entry.protocol_version].format(spec_commit=entry.spec_commit)

    staging = SRC_TYPES_DIR / f"_staging_{entry.module}.py"
    try:
        staging.write_text(header + source)
        run_ruff(staging)
        candidate = staging.read_text()
        assert_only_wire_bases(candidate)
        mod = import_candidate(staging, entry.module)
        audit_candidate(mod, schema, entry)
        audit_meta_carriers(mod, entry)
    finally:
        staging.unlink(missing_ok=True)
    return candidate


def main(argv: list[str] | None = None) -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="diff regenerated output against committed files")
    args = parser.parse_args(argv)

    if importlib.util.find_spec("mcp.types._wire_base") is None:
        raise PipelineError("src/mcp/types/_wire_base.py (WireModel/OpenWireModel) is required")

    entries = load_pinned()
    drifted: list[str] = []
    for entry in entries:
        candidate = build_candidate(entry)
        if args.check:
            committed = entry.target.read_text() if entry.target.is_file() else ""
            if committed == candidate:
                print(f"{entry.protocol_version}: ok ({entry.target.relative_to(REPO_ROOT)})")
            else:
                drifted.append(entry.protocol_version)
                diff = difflib.unified_diff(
                    committed.splitlines(keepends=True),
                    candidate.splitlines(keepends=True),
                    fromfile=str(entry.target.relative_to(REPO_ROOT)),
                    tofile="<regenerated>",
                )
                sys.stderr.writelines(diff)
        else:
            entry.target.parent.mkdir(parents=True, exist_ok=True)
            entry.target.write_text(candidate)
            print(f"{entry.protocol_version}: wrote {entry.target.relative_to(REPO_ROOT)} ({len(candidate)} bytes)")

    if drifted:
        print(
            f"DRIFT: {drifted} differ from committed output; "
            "run `uv run --group codegen python scripts/gen_surface_types.py`",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
