"""Regenerate the per-spec-version oracle modules under tests/spec_oracles/.

Pipeline, per selected entry of tests/spec_oracles/PINNED.json:

1. Fetch ``schema.json`` (and ``schema.ts`` for the protocol-version string) at
   the pinned commit SHA, via ``gh api`` — or read both from ``--schema-dir``.
2. Generate pydantic models with the pinned datamodel-code-generator version,
   invoked through ``uvx`` (no project dependency).
3. Post-process with stdlib ast/re: ``RootModel`` wrappers become type aliases
   (recursive groups become ``TypeAliasType``), the synthetic ``Model`` root
   artifact and stale ``model_rebuild()`` calls are dropped, ``{@link X}``
   JSDoc artifacts are unwrapped, and the per-version rename map is applied.
4. Prepend a provenance header and append the ``SPEC_DEFS`` manifest.
5. ``ruff check --fix`` + ``ruff format`` on a staging file inside
   tests/spec_oracles/ (so the repo config and first-party import
   classification apply); any residual finding other than E501 (per-file-
   ignored for generated modules) aborts the run.
6. Verify: import the staged candidate, audit that every schema definition
   resolves to a module attribute and that field wire names and requiredness
   match the schema. Only then rename into ``tests/spec_oracles/<module>.py``
   and rewrite the derived PINNED.json fields.

Usage (from the repo root)::

    uv run --frozen python scripts/update_spec_types.py [KEY ...] [options]

    KEY            entries to (re)generate: 2024-11-05, 2025-03-26, 2025-06-18,
                   2025-11-25, draft, tasks. Default: all non-frozen entries.
    --all          select every entry.
    --sha SHA      override the pinned SHA for the (single) selected entry and
                   write it back to PINNED.json on success.
    --schema-dir D offline mode: read schemas from D instead of fetching.
                   Naming: schema-<key>.json / schema-<key>.ts for core
                   entries, ext-tasks-schema.json for tasks. The caller asserts
                   the files correspond to the pinned SHAs.
    --check        regenerate and diff against the committed modules; exit 1 on
                   drift, change nothing.
    --force        allow regenerating frozen (released-version) entries.
"""

from __future__ import annotations

import argparse
import ast
import importlib.util
import json
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType
from typing import Any

from pydantic import BaseModel

REPO_ROOT = Path(__file__).resolve().parent.parent
ORACLES_DIR = REPO_ROOT / "tests" / "spec_oracles"
PINNED_PATH = ORACLES_DIR / "PINNED.json"
ALLOWLIST_PATH = ORACLES_DIR / "burndown_allowlist.json"

# Escape hatch for generator name mangling that breaks the def-name audit
# (PINNED key -> {schema def name -> module attribute name}). Entries are added
# only when that audit fails, with a comment citing the colliding def. Matching
# the hand-written SDK's deliberate renames is the burn-down harness's job, not
# the oracle's — oracles stay schema-faithful.
RENAME_MAP: dict[str, dict[str, str]] = {
    "2024-11-05": {},
    "2025-03-26": {},
    "2025-06-18": {},
    "2025-11-25": {},
    "draft": {},
    "tasks": {},
}

_PROTOCOL_VERSION_RE = re.compile(r'LATEST_PROTOCOL_VERSION\s*=\s*"([^"]+)"')
_JSDOC_LINK_RE = re.compile(r"\{@link\s+([^}]+?)\s*\}")
_GENERATOR_BANNER_RE = re.compile(r"\A# generated by datamodel-codegen:\n(#   filename: [^\n]*\n)?\n*")

HEADER_TEMPLATE = """\
# GENERATED FILE — DO NOT EDIT.
# Source: https://github.com/{repo}/blob/{sha}/{schema_path}
# Protocol version: {protocol_version}   Generator: datamodel-code-generator {generator_version}
# Regenerate: uv run --frozen python scripts/update_spec_types.py {key} [--sha <new-sha>]
# pyright: reportIncompatibleVariableOverride=false
"""


class PipelineError(Exception):
    """A stage of the pipeline failed; the message says which and why."""


@dataclass
class Entry:
    """One PINNED.json entry (a core spec version or an extension)."""

    key: str
    repo: str
    sha: str
    schema_path: str
    protocol_version: str | None
    module: str
    frozen: bool
    is_extension: bool


@dataclass
class Outcome:
    """What happened for one regenerated entry (for the final summary)."""

    entry: Entry
    def_count: int
    converted_aliases: int
    recursive_aliases: list[str]
    generator_warnings: list[str]
    e501_count: int
    action: str = ""


@dataclass
class PostprocessResult:
    """Post-processed source plus counters for the summary."""

    source: str
    converted: int
    recursive: list[str]


def load_pinned() -> dict[str, Any]:
    """Read PINNED.json."""
    with PINNED_PATH.open() as f:
        return json.load(f)


def iter_entries(pinned: dict[str, Any]) -> list[Entry]:
    """Flatten PINNED.json into Entry records (core versions, then extensions)."""
    entries: list[Entry] = []
    for key, data in pinned["versions"].items():
        entries.append(
            Entry(
                key=key,
                repo=pinned["spec_repo"],
                sha=data["sha"],
                schema_path=data["schema_path"],
                protocol_version=data["protocol_version"],
                module=data["module"],
                frozen=data["frozen"],
                is_extension=False,
            )
        )
    for key, data in pinned["extensions"].items():
        entries.append(
            Entry(
                key=key,
                repo=data["repo"],
                sha=data["sha"],
                schema_path=data["schema_path"],
                protocol_version=data["protocol_version"],
                module=data["module"],
                frozen=data["frozen"],
                is_extension=True,
            )
        )
    return entries


def gh_fetch(repo: str, path: str, sha: str) -> str:
    """Fetch one file from GitHub at a pinned SHA via `gh api`."""
    result = subprocess.run(
        [
            "gh",
            "api",
            "-H",
            "Accept: application/vnd.github.raw+json",
            f"repos/{repo}/contents/{path}?ref={sha}",
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise PipelineError(f"gh api fetch of {repo}:{path}@{sha} failed: {result.stderr.strip()}")
    return result.stdout


def obtain_schemas(entry: Entry, sha: str, schema_dir: Path | None) -> tuple[str, str | None]:
    """Return (schema.json text, schema.ts text or None) for an entry."""
    if schema_dir is not None:
        if entry.is_extension:
            json_path, ts_path = schema_dir / "ext-tasks-schema.json", None
        else:
            json_path = schema_dir / f"schema-{entry.key}.json"
            ts_path = schema_dir / f"schema-{entry.key}.ts"
        if not json_path.is_file():
            raise PipelineError(f"{entry.key}: --schema-dir is missing {json_path.name}")
        ts_text: str | None = None
        if ts_path is not None:
            if not ts_path.is_file():
                raise PipelineError(f"{entry.key}: --schema-dir is missing {ts_path.name}")
            ts_text = ts_path.read_text()
        return json_path.read_text(), ts_text
    schema_json = gh_fetch(entry.repo, entry.schema_path, sha)
    ts_text = None
    if not entry.is_extension:
        ts_remote_path = entry.schema_path.removesuffix("schema.json") + "schema.ts"
        ts_text = gh_fetch(entry.repo, ts_remote_path, sha)
    return schema_json, ts_text


def extract_protocol_version(entry: Entry, ts_text: str | None) -> str | None:
    """Extract LATEST_PROTOCOL_VERSION from schema.ts; None for extensions."""
    if entry.is_extension:
        return None
    if ts_text is None:
        raise PipelineError(f"{entry.key}: schema.ts is required to extract the protocol version")
    match = _PROTOCOL_VERSION_RE.search(ts_text)
    if match is None:
        raise PipelineError(f"{entry.key}: LATEST_PROTOCOL_VERSION not found in schema.ts")
    version = match.group(1)
    if entry.key != "draft" and version != entry.key:
        raise PipelineError(
            f"{entry.key}: released schema.ts declares LATEST_PROTOCOL_VERSION={version!r}; "
            "released schemas are immutable, so this indicates a wrong SHA or schema file"
        )
    return version


def module_name_for(entry: Entry, protocol_version: str | None) -> str:
    """Derive the oracle module name from the protocol version string."""
    if entry.is_extension:
        return f"ext_{entry.key}"
    if protocol_version is None:
        raise PipelineError(f"{entry.key}: cannot derive a module name without a protocol version")
    return "v" + re.sub(r"[^a-z0-9]+", "_", protocol_version.lower())


def run_generator(schema_json_path: Path, output_path: Path, generator_version: str) -> list[str]:
    """Run the pinned datamodel-code-generator via uvx; return its warning lines."""
    result = subprocess.run(
        [
            "uvx",
            "--from",
            f"datamodel-code-generator=={generator_version}",
            "datamodel-codegen",
            "--input",
            str(schema_json_path),
            "--input-file-type",
            "jsonschema",
            "--output",
            str(output_path),
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--target-python-version",
            "3.10",
            "--base-class",
            "tests.spec_oracles._base.OracleModel",
            "--snake-case-field",
            "--remove-special-field-name-prefix",
            "--use-annotated",
            "--use-field-description",
            "--use-schema-description",
            "--enum-field-as-literal",
            "all",
            "--use-union-operator",
            "--use-double-quotes",
            "--extra-fields",
            "allow",
            "--disable-timestamp",
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0 or not output_path.is_file():
        raise PipelineError(f"datamodel-codegen failed:\n{result.stderr.strip()}")
    return [line for line in result.stderr.splitlines() if "Warning" in line and "FutureWarning" not in line]


def _collect_rootmodel_aliases(tree: ast.Module) -> dict[str, tuple[ast.ClassDef, str]]:
    """Map class name -> (node, unparsed RootModel type argument) for RootModel subclasses."""
    aliases: dict[str, tuple[ast.ClassDef, str]] = {}
    for node in tree.body:
        if not isinstance(node, ast.ClassDef) or len(node.bases) != 1:
            continue
        base = node.bases[0]
        if isinstance(base, ast.Subscript) and isinstance(base.value, ast.Name) and base.value.id == "RootModel":
            aliases[node.name] = (node, ast.unparse(base.slice))
    return aliases


def _find_recursive_aliases(aliases: dict[str, tuple[ast.ClassDef, str]]) -> set[str]:
    """Names of alias classes that participate in a reference cycle."""

    def refs(type_expr: str) -> set[str]:
        bare = type_expr.replace("'", " ").replace('"', " ")
        return {name for name in aliases if re.search(rf"\b{name}\b", bare)}

    cyclic: set[str] = set()
    for name, (_, type_expr) in aliases.items():
        seen: set[str] = set()
        stack = list(refs(type_expr))
        while stack:
            current = stack.pop()
            if current == name:
                cyclic.add(name)
                break
            if current in seen or current not in aliases:
                continue
            seen.add(current)
            stack.extend(refs(aliases[current][1]))
    return cyclic


def _alias_statement(name: str, node: ast.ClassDef, alias_type: str, *, string_form: bool) -> str:
    """One converted alias definition (docstring preserved as a trailing string)."""
    if string_form:
        value = alias_type.replace("'", "").replace('"', "")
        text = f'{name} = TypeAliasType("{name}", "{value}")\n'
    else:
        text = f'{name} = TypeAliasType("{name}", {alias_type})\n'
    docstring = ast.get_docstring(node)
    if docstring and '"""' not in docstring:
        text += '"""' + docstring + '"""\n'
    return text


def _emit_cyclic_block(ordered: list[str], aliases: dict[str, tuple[ast.ClassDef, str]]) -> str:
    """Emit a group of mutually recursive aliases in the one form pyright accepts.

    Empirical pyright (1.1.405) behavior for call-form TypeAliasType groups:
    quoted self-references in an expression-form value error with
    reportInvalidTypeForm whenever the value also references another cyclic
    alias, quoted forward references from expression-form values error
    unconditionally, and any emission errors if a usage site precedes the
    definitions. The working emission is: members whose value references
    itself go first as a whole-string value (lazily parsed), the remaining
    members follow in expression form so their quoted references point
    backwards — and the whole block must be placed before its first use
    (the caller relocates it to just after the imports).
    """

    def has_self_ref(name: str) -> bool:
        bare = aliases[name][1].replace("'", " ").replace('"', " ")
        return re.search(rf"\b{name}\b", bare) is not None

    string_members = [n for n in ordered if has_self_ref(n)]
    expr_members = [n for n in ordered if not has_self_ref(n)]
    parts = [
        _alias_statement(name, aliases[name][0], aliases[name][1], string_form=name in string_members)
        for name in [*string_members, *expr_members]
    ]
    return "\n\n".join(parts)


# Names a relocated cyclic-alias block may reference besides its own members:
# anything else means relocation could break runtime evaluation order.
_RELOCATABLE_NAMES = frozenset(
    {"Annotated", "Any", "Literal", "None", "Optional", "Union"}
    | {"bool", "bytes", "dict", "float", "frozenset", "int", "list", "set", "str", "tuple"}
)


def _group_is_self_contained(cyclic: set[str], aliases: dict[str, tuple[ast.ClassDef, str]]) -> bool:
    """True if the cyclic group references only its own members and builtins."""
    allowed = cyclic | _RELOCATABLE_NAMES
    for name in cyclic:
        bare = aliases[name][1].replace("'", " ").replace('"', " ")
        identifiers = set(re.findall(r"[A-Za-z_][A-Za-z0-9_]*", bare))
        if not identifiers <= allowed:
            return False
    return True


def _end_lineno(node: ast.stmt) -> int:
    """End line of a statement (ast fills end_lineno in for parsed code)."""
    end = node.end_lineno
    if end is None:
        raise PipelineError(f"ast node at line {node.lineno} has no end_lineno")
    return end


def postprocess(source: str, rename_map: dict[str, str]) -> PostprocessResult:
    """Convert RootModel wrappers to aliases and clean up generator artifacts."""
    source = _GENERATOR_BANNER_RE.sub("", source)
    tree = ast.parse(source)
    lines = source.splitlines(keepends=True)

    aliases = _collect_rootmodel_aliases(tree)
    cyclic = _find_recursive_aliases(aliases)

    converted = 0
    cyclic_in_order = [name for name in aliases if name in cyclic]
    relocate = bool(cyclic) and _group_is_self_contained(cyclic, aliases)
    replacements: list[tuple[int, int, str]] = []  # 1-based inclusive line ranges
    for name, (node, alias_type) in aliases.items():
        if name == "Model" and alias_type == "Any":
            # The generator's synthetic artifact for the schema's empty root.
            replacements.append((node.lineno, _end_lineno(node), ""))
            continue
        if name in cyclic:
            # The whole group is emitted as one block (see _emit_cyclic_block):
            # relocated to just after the imports when self-contained, else at
            # the first member's position (pyright will flag usage-before-
            # definition there; that is an escalation, not a workaround site).
            if relocate or name != cyclic_in_order[0]:
                new = ""
            else:
                new = _emit_cyclic_block(cyclic_in_order, aliases)
        else:
            new = f"{name}: TypeAlias = {alias_type}\n"
            docstring = ast.get_docstring(node)
            if docstring and '"""' not in docstring:
                new += '"""' + docstring + '"""\n'
        replacements.append((node.lineno, _end_lineno(node), new))
        converted += 1
    if relocate:
        last_import_end = max(_end_lineno(node) for node in tree.body if isinstance(node, ast.Import | ast.ImportFrom))
        block = _emit_cyclic_block(cyclic_in_order, aliases)
        replacements.append((last_import_end, last_import_end, lines[last_import_end - 1] + "\n" + block))

    # Import fixes, on the same parsed tree: drop RootModel from the pydantic
    # import, add TypeAlias / TypeAliasType imports where the conversions need
    # them. ruff's import sorting normalizes placement afterwards.
    need_type_alias = converted > len(cyclic)
    need_type_alias_type = bool(cyclic)
    typing_handled = False
    for node in tree.body:
        if not isinstance(node, ast.ImportFrom):
            continue
        if node.module == "pydantic":
            names = [alias for alias in node.names if alias.name != "RootModel"]
            text = ast.unparse(ast.ImportFrom(module="pydantic", names=names, level=0)) + "\n" if names else ""
            replacements.append((node.lineno, _end_lineno(node), text))
        elif node.module == "typing":
            typing_handled = True
            names = list(node.names)
            if need_type_alias and not any(alias.name == "TypeAlias" for alias in names):
                names.append(ast.alias(name="TypeAlias"))
            text = ast.unparse(ast.ImportFrom(module="typing", names=names, level=0)) + "\n"
            if need_type_alias_type:
                text += "from typing_extensions import TypeAliasType\n"
            replacements.append((node.lineno, _end_lineno(node), text))
    if not typing_handled and (need_type_alias or need_type_alias_type):
        extra = "from typing import TypeAlias\n" if need_type_alias else ""
        if need_type_alias_type:
            extra += "from typing_extensions import TypeAliasType\n"
        for node in tree.body:
            if isinstance(node, ast.ImportFrom) and node.module == "__future__":
                replacements.append((node.lineno, _end_lineno(node), lines[node.lineno - 1] + extra))
                break

    for start, end, new in sorted(replacements, reverse=True):
        lines[start - 1 : end] = [new]
    source = "".join(lines)

    # model_rebuild() is only valid on classes; drop calls for converted names.
    for name in [*aliases, "Model"]:
        source = re.sub(rf"^{name}\.model_rebuild\(\)\n", "", source, flags=re.MULTILINE)

    source = _JSDOC_LINK_RE.sub(r"\1", source)

    for old, new_name in rename_map.items():
        source = re.sub(rf"\b{old}\b", new_name, source)

    return PostprocessResult(source=source, converted=converted, recursive=sorted(cyclic))


def schema_defs(schema: dict[str, Any]) -> dict[str, Any]:
    """The definitions table of a schema ($defs in 2020-12, definitions in draft-07)."""
    defs = schema.get("$defs") or schema.get("definitions")
    if not defs:
        raise PipelineError("schema has no $defs/definitions table")
    return defs


def build_manifest(schema: dict[str, Any], rename_map: dict[str, str]) -> str:
    """Render the SPEC_DEFS manifest appended to each generated module."""
    names = sorted(rename_map.get(name, name) for name in schema_defs(schema))
    body = "".join(f'    "{name}",\n' for name in names)
    return f"\nSPEC_DEFS: tuple[str, ...] = (\n{body})\n"


def run_ruff(path: Path) -> int:
    """ruff check --fix + format with the repo config; return the residual E501 count.

    Any residual finding other than E501 (which is per-file-ignored for the
    generated modules once installed) aborts the pipeline.
    """
    common = ["uv", "run", "--frozen", "ruff"]
    fix = subprocess.run(
        [*common, "check", "--no-cache", "--fix", "--exit-zero", str(path)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if fix.returncode != 0:
        raise PipelineError(f"ruff check --fix failed:\n{fix.stderr.strip()}")
    report = subprocess.run(
        [*common, "check", "--no-cache", "--output-format", "json", "--exit-zero", str(path)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if report.returncode != 0:
        raise PipelineError(f"ruff check (report) failed:\n{report.stderr.strip()}")
    findings: list[dict[str, Any]] = json.loads(report.stdout)
    residual = [f for f in findings if f.get("code") != "E501"]
    if residual:
        details = "\n".join(
            f"  {f.get('code')}: {f.get('message')} (line {f.get('location', {}).get('row')})" for f in residual
        )
        raise PipelineError(f"ruff residual findings other than E501 in {path.name}:\n{details}")
    fmt = subprocess.run([*common, "format", "--no-cache", str(path)], cwd=REPO_ROOT, capture_output=True, text=True)
    if fmt.returncode != 0:
        raise PipelineError(f"ruff format failed:\n{fmt.stderr.strip()}")
    return len(findings) - len(residual)


def load_schema_gap_exemptions(module: str) -> set[tuple[str, str | None]]:
    """(def name, field-or-None) audit exemptions: allowlist entries categorized schema-gap."""
    if not ALLOWLIST_PATH.is_file():
        return set()
    with ALLOWLIST_PATH.open() as f:
        allowlist: dict[str, Any] = json.load(f)
    return {
        (entry["name"], entry.get("field"))
        for entry in allowlist.get("entries", [])
        if entry.get("category") == "schema-gap" and entry.get("oracle") == module
    }


def import_candidate(path: Path, module: str) -> ModuleType:
    """Import a staged candidate module under a private name."""
    name = f"_oracle_candidate_{module}"
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise PipelineError(f"cannot load candidate module from {path}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def audit_candidate(mod: ModuleType, schema: dict[str, Any], entry: Entry, rename_map: dict[str, str]) -> None:
    """Def-name + alias + requiredness audit; raises on any failure."""
    problems: list[str] = []
    exempt = load_schema_gap_exemptions(entry.module)
    for def_name, def_schema in schema_defs(schema).items():
        attr = rename_map.get(def_name, def_name)
        obj = getattr(mod, attr, None)
        if obj is None:
            problems.append(f"def {def_name!r} does not resolve to attribute {attr!r}")
            continue
        if not (isinstance(obj, type) and issubclass(obj, BaseModel)):
            continue  # type aliases / Literal aliases have no fields to audit
        if (attr, None) in exempt:
            continue
        properties: dict[str, Any] = def_schema.get("properties", {})
        required: list[str] = def_schema.get("required", [])
        fields_by_wire_name = {
            (info.serialization_alias or info.alias or field_name): info
            for field_name, info in obj.model_fields.items()
        }
        for prop_name in properties:
            if (attr, prop_name) in exempt:
                continue
            info = fields_by_wire_name.get(prop_name)
            if info is None:
                problems.append(f"{attr}: no field with wire name {prop_name!r}")
                continue
            if info.is_required() != (prop_name in required):
                problems.append(
                    f"{attr}.{prop_name}: requiredness mismatch "
                    f"(model={info.is_required()}, schema={prop_name in required})"
                )
    if problems:
        raise PipelineError(f"{entry.key}: audit failed:\n" + "\n".join(f"  - {p}" for p in problems))


def import_check(module: str) -> None:
    """The official post-install import gate, in a clean subprocess from the repo root."""
    result = subprocess.run(
        ["uv", "run", "--frozen", "python", "-c", f"import tests.spec_oracles.{module}"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise PipelineError(f"import check failed for tests.spec_oracles.{module}:\n{result.stderr.strip()}")


def build_candidate(entry: Entry, sha: str, schema_dir: Path | None, generator_version: str) -> tuple[str, Outcome]:
    """Stages 1-6 (through the audit) for one entry; returns (candidate source, outcome)."""
    schema_json_text, ts_text = obtain_schemas(entry, sha, schema_dir)
    schema: dict[str, Any] = json.loads(schema_json_text)
    protocol_version = extract_protocol_version(entry, ts_text)
    entry.protocol_version = protocol_version
    entry.module = module_name_for(entry, protocol_version)
    entry.sha = sha
    rename_map = RENAME_MAP[entry.key]

    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        schema_file = tmp_dir / "schema.json"
        schema_file.write_text(schema_json_text)
        raw_file = tmp_dir / "raw.py"
        warnings = run_generator(schema_file, raw_file, generator_version)
        processed = postprocess(raw_file.read_text(), rename_map)

    header = HEADER_TEMPLATE.format(
        repo=entry.repo,
        sha=sha,
        schema_path=entry.schema_path,
        protocol_version=entry.protocol_version or "n/a",
        generator_version=generator_version,
        key=entry.key,
    )
    # Staged inside the package so ruff applies the repo config with in-repo
    # first-party import classification, and so the audit import resolves
    # `tests.spec_oracles._base` the same way the installed module will.
    staging = ORACLES_DIR / f"_staging_{entry.module}.py"
    try:
        staging.write_text(header + processed.source + build_manifest(schema, rename_map))
        e501_count = run_ruff(staging)
        mod = import_candidate(staging, entry.module)
        audit_candidate(mod, schema, entry, rename_map)
        candidate = staging.read_text()
    finally:
        staging.unlink(missing_ok=True)

    outcome = Outcome(
        entry=entry,
        def_count=len(schema_defs(schema)),
        converted_aliases=processed.converted,
        recursive_aliases=processed.recursive,
        generator_warnings=warnings,
        e501_count=e501_count,
    )
    return candidate, outcome


def write_back_pinned(pinned: dict[str, Any], entries: list[Entry]) -> None:
    """Rewrite the derived fields (sha, protocol_version, module) into PINNED.json."""
    by_key = {e.key: e for e in entries}
    for table in (pinned["versions"], pinned["extensions"]):
        for key, data in table.items():
            if key in by_key:
                entry = by_key[key]
                data["sha"] = entry.sha
                data["protocol_version"] = entry.protocol_version
                data["module"] = entry.module
    PINNED_PATH.write_text(json.dumps(pinned, indent=2) + "\n")


def delete_orphans(pinned: dict[str, Any]) -> list[str]:
    """Delete generated modules that no PINNED.json entry produces any more."""
    known = {data["module"] for data in pinned["versions"].values()}
    known |= {data["module"] for data in pinned["extensions"].values()}
    deleted: list[str] = []
    for path in sorted(ORACLES_DIR.glob("*.py")):
        if path.stem.startswith(("_", "test_")) or path.name == "__init__.py":
            continue
        if path.stem not in known:
            path.unlink()
            deleted.append(path.name)
    return deleted


def summarize(outcomes: list[Outcome]) -> None:
    """Print the per-entry generation summary."""
    for o in outcomes:
        print(
            f"{o.entry.key}: {o.action} -> tests/spec_oracles/{o.entry.module}.py "
            f"(defs={o.def_count}, alias_conversions={o.converted_aliases}, "
            f"recursive={o.recursive_aliases or 'none'}, residual_E501={o.e501_count})"
        )
        for warning in o.generator_warnings:
            print(f"  generator warning: {warning}")


def main(argv: list[str] | None = None) -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("keys", nargs="*", help="PINNED.json entries to regenerate (default: all non-frozen)")
    parser.add_argument("--all", action="store_true", help="select every entry")
    parser.add_argument("--sha", help="override the pinned SHA (single KEY only); written back on success")
    parser.add_argument("--schema-dir", type=Path, help="read schemas from this directory instead of fetching")
    parser.add_argument("--check", action="store_true", help="diff regenerated output against committed modules")
    parser.add_argument("--force", action="store_true", help="allow regenerating frozen entries")
    args = parser.parse_args(argv)

    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))

    pinned = load_pinned()
    entries = iter_entries(pinned)
    valid_keys = [e.key for e in entries]
    if args.all:
        selected = entries
    elif args.keys:
        unknown = [k for k in args.keys if k not in valid_keys]
        if unknown:
            parser.error(f"unknown KEY(s) {unknown}; valid: {valid_keys}")
        selected = [e for e in entries if e.key in args.keys]
    else:
        selected = [e for e in entries if not e.frozen]
    if args.sha and len(selected) != 1:
        parser.error("--sha requires exactly one KEY")

    generator_version: str = pinned["generator"]["version"]
    outcomes: list[Outcome] = []
    drifted: list[str] = []
    regenerated: list[Entry] = []
    for entry in selected:
        target = ORACLES_DIR / f"{entry.module}.py"
        if entry.frozen and target.is_file() and not (args.force or args.check):
            print(f"{entry.key}: frozen (released schemas are generate-once); use --force to regenerate")
            continue
        candidate, outcome = build_candidate(entry, args.sha or entry.sha, args.schema_dir, generator_version)
        target = ORACLES_DIR / f"{entry.module}.py"  # module may have been re-derived
        if args.check:
            if target.is_file() and target.read_text() == candidate:
                outcome.action = "checked"
            else:
                outcome.action = "drifted"
                drifted.append(entry.module)
        else:
            if target.is_file() and target.read_text() == candidate:
                outcome.action = "unchanged"
            else:
                target.write_text(candidate)
                outcome.action = "installed"
            import_check(entry.module)
            regenerated.append(entry)
        outcomes.append(outcome)

    if regenerated and not args.check:
        write_back_pinned(pinned, regenerated)
        for name in delete_orphans(pinned):
            print(f"deleted orphaned module: {name}")

    summarize(outcomes)
    if drifted:
        print(f"DRIFT: {drifted} differ from committed output", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
