"""Regenerate the spec-version model modules (test oracles and src packages).

Two output flavors share one fetch -> generate -> post-process core:

``--oracle`` (default) regenerates the per-spec-version oracle modules under
tests/spec_oracles/. Pipeline, per selected entry of tests/spec_oracles/PINNED.json:

1. Fetch ``schema.json`` (and ``schema.ts`` for the protocol-version string) at
   the pinned commit SHA, via ``gh api`` — or read both from ``--schema-dir``.
2. Generate pydantic models with the pinned datamodel-code-generator version,
   invoked through ``uvx`` (no project dependency).
3. Post-process with stdlib ast/re: ``RootModel`` wrappers become type aliases
   (recursive groups become ``TypeAliasType``), the synthetic ``Model`` root
   artifact and stale ``model_rebuild()`` calls are dropped, ``{@link X}``
   JSDoc artifacts are unwrapped, and the per-version rename map is applied.
4. Prepend a provenance header and append the ``SPEC_DEFS`` manifest.
5. ``ruff check --fix`` + ``ruff format`` on a staging file inside
   tests/spec_oracles/ (so the repo config and first-party import
   classification apply); any residual finding other than E501 (per-file-
   ignored for generated modules) aborts the run.
6. Verify: import the staged candidate, audit that every schema definition
   resolves to a module attribute and that field wire names and requiredness
   match the schema. Only then rename into ``tests/spec_oracles/<module>.py``
   and rewrite the derived PINNED.json fields.

``--src`` scaffolds the committed per-version wire-model packages under
src/mcp/types/v<version>/. Same core, then the source passes documented on
each pass function below (value-type downgrades, per-class extra policy,
``_meta``-carrier rebasing, inheritance flattening, deterministic synthetic
names, early content arms, docstring wrapping, provenance docstring), a strict
ruff stage (no residual findings at all), and the import-time audits. It is a
scaffold, not a sync mechanism: it refuses to overwrite an existing package
without ``--force``, and the emitted packages are maintained as ordinary
source afterwards.

Usage (from the repo root)::

    uv run --frozen python scripts/update_spec_types.py [KEY ...] [options]

    KEY            entries to (re)generate: 2024-11-05, 2025-03-26, 2025-06-18,
                   2025-11-25, draft. Default: all non-frozen entries.
    --all          select every entry.
    --src          emit src/mcp/types/v<version>/__init__.py packages instead
                   of test oracles.
    --sha SHA      override the pinned SHA for the (single) selected entry and
                   write it back to PINNED.json on success (oracle mode only).
    --schema-dir D offline mode: read schemas from D instead of fetching.
                   Naming: schema-<key>.json / schema-<key>.ts. The caller
                   asserts the files correspond to the pinned SHAs.
    --check        regenerate and diff against the committed modules; exit 1 on
                   drift, change nothing.
    --force        allow regenerating frozen (released-version) oracle entries,
                   or overwriting an existing src package.
"""

from __future__ import annotations

import argparse
import ast
import importlib.util
import json
import re
import subprocess
import sys
import tempfile
import textwrap
import typing
from dataclasses import dataclass, field
from pathlib import Path
from types import ModuleType
from typing import Any

from pydantic import BaseModel

REPO_ROOT = Path(__file__).resolve().parent.parent
ORACLES_DIR = REPO_ROOT / "tests" / "spec_oracles"
SRC_TYPES_DIR = REPO_ROOT / "src" / "mcp" / "types"
PINNED_PATH = ORACLES_DIR / "PINNED.json"

# Escape hatch for generator name mangling that breaks the def-name audit
# (PINNED key -> {schema def name -> module attribute name}). Entries are added
# only when that audit fails, with a comment citing the colliding def. Matching
# the hand-written SDK's deliberate renames is the burn-down harness's job, not
# the oracle's — oracles stay schema-faithful.
RENAME_MAP: dict[str, dict[str, str]] = {
    "2024-11-05": {},
    "2025-03-26": {},
    "2025-06-18": {},
    "2025-11-25": {},
    "draft": {},
}

_PROTOCOL_VERSION_RE = re.compile(r'LATEST_PROTOCOL_VERSION\s*=\s*"([^"]+)"')
_JSDOC_LINK_RE = re.compile(r"\{@link\s+([^}]+?)\s*\}")
_GENERATOR_BANNER_RE = re.compile(r"\A# generated by datamodel-codegen:\n(#   filename: [^\n]*\n)?\n*")
_FIELD_ALIAS_RE = re.compile(r"alias=['\"]([^'\"]+)['\"]")

HEADER_TEMPLATE = """\
# GENERATED FILE — DO NOT EDIT.
# Source: https://github.com/{repo}/blob/{sha}/{schema_path}
# Protocol version: {protocol_version}   Generator: datamodel-code-generator {generator_version}
# Regenerate: uv run --frozen python scripts/update_spec_types.py {key} [--sha <new-sha>]
# pyright: reportIncompatibleVariableOverride=false
"""


class PipelineError(Exception):
    """A stage of the pipeline failed; the message says which and why."""


@dataclass
class Entry:
    """One PINNED.json entry (a core spec version or an extension)."""

    key: str
    repo: str
    sha: str
    schema_path: str
    protocol_version: str | None
    module: str
    frozen: bool
    is_extension: bool


@dataclass
class Outcome:
    """What happened for one regenerated entry (for the final summary)."""

    entry: Entry
    def_count: int
    converted_aliases: int
    recursive_aliases: list[str]
    generator_warnings: list[str]
    e501_count: int
    action: str = ""
    src_notes: list[str] = field(default_factory=list)


@dataclass
class PostprocessResult:
    """Post-processed source plus counters for the summary."""

    source: str
    converted: int
    recursive: list[str]


def load_pinned() -> dict[str, Any]:
    """Read PINNED.json."""
    with PINNED_PATH.open() as f:
        return json.load(f)


def iter_entries(pinned: dict[str, Any]) -> list[Entry]:
    """Flatten PINNED.json into Entry records (core versions, then extensions)."""
    entries: list[Entry] = []
    for key, data in pinned["versions"].items():
        entries.append(
            Entry(
                key=key,
                repo=pinned["spec_repo"],
                sha=data["sha"],
                schema_path=data["schema_path"],
                protocol_version=data["protocol_version"],
                module=data["module"],
                frozen=data["frozen"],
                is_extension=False,
            )
        )
    for key, data in pinned["extensions"].items():
        entries.append(
            Entry(
                key=key,
                repo=data["repo"],
                sha=data["sha"],
                schema_path=data["schema_path"],
                protocol_version=data["protocol_version"],
                module=data["module"],
                frozen=data["frozen"],
                is_extension=True,
            )
        )
    return entries


def gh_fetch(repo: str, path: str, sha: str) -> str:
    """Fetch one file from GitHub at a pinned SHA via `gh api`."""
    result = subprocess.run(
        [
            "gh",
            "api",
            "-H",
            "Accept: application/vnd.github.raw+json",
            f"repos/{repo}/contents/{path}?ref={sha}",
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise PipelineError(f"gh api fetch of {repo}:{path}@{sha} failed: {result.stderr.strip()}")
    return result.stdout


def obtain_schemas(entry: Entry, sha: str, schema_dir: Path | None) -> tuple[str, str]:
    """Return (schema.json text, schema.ts text) for an entry."""
    if schema_dir is not None:
        json_path = schema_dir / f"schema-{entry.key}.json"
        ts_path = schema_dir / f"schema-{entry.key}.ts"
        if not json_path.is_file():
            raise PipelineError(f"{entry.key}: --schema-dir is missing {json_path.name}")
        if not ts_path.is_file():
            raise PipelineError(f"{entry.key}: --schema-dir is missing {ts_path.name}")
        return json_path.read_text(), ts_path.read_text()
    schema_json = gh_fetch(entry.repo, entry.schema_path, sha)
    ts_remote_path = entry.schema_path.removesuffix("schema.json") + "schema.ts"
    ts_text = gh_fetch(entry.repo, ts_remote_path, sha)
    return schema_json, ts_text


def extract_protocol_version(entry: Entry, ts_text: str) -> str:
    """Extract LATEST_PROTOCOL_VERSION from schema.ts."""
    match = _PROTOCOL_VERSION_RE.search(ts_text)
    if match is None:
        raise PipelineError(f"{entry.key}: LATEST_PROTOCOL_VERSION not found in schema.ts")
    version = match.group(1)
    if entry.key != "draft" and version != entry.key:
        raise PipelineError(
            f"{entry.key}: released schema.ts declares LATEST_PROTOCOL_VERSION={version!r}; "
            "released schemas are immutable, so this indicates a wrong SHA or schema file"
        )
    return version


def module_name_for(protocol_version: str) -> str:
    """Derive the module name from the protocol version string."""
    return "v" + re.sub(r"[^a-z0-9]+", "_", protocol_version.lower())


def run_generator(schema_json_path: Path, output_path: Path, generator_version: str, base_class: str) -> list[str]:
    """Run the pinned datamodel-code-generator via uvx; return its warning lines."""
    result = subprocess.run(
        [
            "uvx",
            "--from",
            f"datamodel-code-generator=={generator_version}",
            "datamodel-codegen",
            "--input",
            str(schema_json_path),
            "--input-file-type",
            "jsonschema",
            "--output",
            str(output_path),
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--target-python-version",
            "3.10",
            "--base-class",
            base_class,
            "--snake-case-field",
            "--remove-special-field-name-prefix",
            "--use-annotated",
            "--use-field-description",
            "--use-schema-description",
            "--enum-field-as-literal",
            "all",
            "--use-union-operator",
            "--use-double-quotes",
            "--extra-fields",
            "allow",
            "--disable-timestamp",
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0 or not output_path.is_file():
        raise PipelineError(f"datamodel-codegen failed:\n{result.stderr.strip()}")
    return [line for line in result.stderr.splitlines() if "Warning" in line and "FutureWarning" not in line]


def _collect_rootmodel_aliases(tree: ast.Module) -> dict[str, tuple[ast.ClassDef, str]]:
    """Map class name -> (node, unparsed RootModel type argument) for RootModel subclasses."""
    aliases: dict[str, tuple[ast.ClassDef, str]] = {}
    for node in tree.body:
        if not isinstance(node, ast.ClassDef) or len(node.bases) != 1:
            continue
        base = node.bases[0]
        if isinstance(base, ast.Subscript) and isinstance(base.value, ast.Name) and base.value.id == "RootModel":
            aliases[node.name] = (node, ast.unparse(base.slice))
    return aliases


def _find_recursive_aliases(aliases: dict[str, tuple[ast.ClassDef, str]]) -> set[str]:
    """Names of alias classes that participate in a reference cycle."""

    def refs(type_expr: str) -> set[str]:
        bare = type_expr.replace("'", " ").replace('"', " ")
        return {name for name in aliases if re.search(rf"\b{name}\b", bare)}

    cyclic: set[str] = set()
    for name, (_, type_expr) in aliases.items():
        seen: set[str] = set()
        stack = list(refs(type_expr))
        while stack:
            current = stack.pop()
            if current == name:
                cyclic.add(name)
                break
            if current in seen or current not in aliases:
                continue
            seen.add(current)
            stack.extend(refs(aliases[current][1]))
    return cyclic


def _alias_statement(name: str, node: ast.ClassDef, alias_type: str, *, string_form: bool) -> str:
    """One converted alias definition (docstring preserved as a trailing string)."""
    if string_form:
        value = alias_type.replace("'", "").replace('"', "")
        text = f'{name} = TypeAliasType("{name}", "{value}")\n'
    else:
        text = f'{name} = TypeAliasType("{name}", {alias_type})\n'
    docstring = ast.get_docstring(node)
    if docstring and '"""' not in docstring:
        text += '"""' + docstring + '"""\n'
    return text


def _emit_cyclic_block(ordered: list[str], aliases: dict[str, tuple[ast.ClassDef, str]]) -> str:
    """Emit a group of mutually recursive aliases in the one form pyright accepts.

    Empirical pyright (1.1.405) behavior for call-form TypeAliasType groups:
    quoted self-references in an expression-form value error with
    reportInvalidTypeForm whenever the value also references another cyclic
    alias, quoted forward references from expression-form values error
    unconditionally, and any emission errors if a usage site precedes the
    definitions. The working emission is: members whose value references
    itself go first as a whole-string value (lazily parsed), the remaining
    members follow in expression form so their quoted references point
    backwards — and the whole block must be placed before its first use
    (the caller relocates it to just after the imports).
    """

    def has_self_ref(name: str) -> bool:
        bare = aliases[name][1].replace("'", " ").replace('"', " ")
        return re.search(rf"\b{name}\b", bare) is not None

    string_members = [n for n in ordered if has_self_ref(n)]
    expr_members = [n for n in ordered if not has_self_ref(n)]
    parts = [
        _alias_statement(name, aliases[name][0], aliases[name][1], string_form=name in string_members)
        for name in [*string_members, *expr_members]
    ]
    return "\n\n".join(parts)


# Names a relocated cyclic-alias block may reference besides its own members:
# anything else means relocation could break runtime evaluation order.
_RELOCATABLE_NAMES = frozenset(
    {"Annotated", "Any", "Literal", "None", "Optional", "Union"}
    | {"bool", "bytes", "dict", "float", "frozenset", "int", "list", "set", "str", "tuple"}
)


def _group_is_self_contained(cyclic: set[str], aliases: dict[str, tuple[ast.ClassDef, str]]) -> bool:
    """True if the cyclic group references only its own members and builtins."""
    allowed = cyclic | _RELOCATABLE_NAMES
    for name in cyclic:
        bare = aliases[name][1].replace("'", " ").replace('"', " ")
        identifiers = set(re.findall(r"[A-Za-z_][A-Za-z0-9_]*", bare))
        if not identifiers <= allowed:
            return False
    return True


def _end_lineno(node: ast.stmt) -> int:
    """End line of a statement (ast fills end_lineno in for parsed code)."""
    end = node.end_lineno
    if end is None:
        raise PipelineError(f"ast node at line {node.lineno} has no end_lineno")
    return end


def postprocess(source: str, rename_map: dict[str, str]) -> PostprocessResult:
    """Convert RootModel wrappers to aliases and clean up generator artifacts."""
    source = _GENERATOR_BANNER_RE.sub("", source)
    tree = ast.parse(source)
    lines = source.splitlines(keepends=True)

    aliases = _collect_rootmodel_aliases(tree)
    cyclic = _find_recursive_aliases(aliases)

    converted = 0
    cyclic_in_order = [name for name in aliases if name in cyclic]
    relocate = bool(cyclic) and _group_is_self_contained(cyclic, aliases)
    replacements: list[tuple[int, int, str]] = []  # 1-based inclusive line ranges
    for name, (node, alias_type) in aliases.items():
        if name == "Model" and alias_type == "Any":
            # The generator's synthetic artifact for the schema's empty root.
            replacements.append((node.lineno, _end_lineno(node), ""))
            continue
        if name in cyclic:
            # The whole group is emitted as one block (see _emit_cyclic_block):
            # relocated to just after the imports when self-contained, else at
            # the first member's position (pyright will flag usage-before-
            # definition there; that is an escalation, not a workaround site).
            if relocate or name != cyclic_in_order[0]:
                new = ""
            else:
                new = _emit_cyclic_block(cyclic_in_order, aliases)
        else:
            new = f"{name}: TypeAlias = {alias_type}\n"
            docstring = ast.get_docstring(node)
            if docstring and '"""' not in docstring:
                new += '"""' + docstring + '"""\n'
        replacements.append((node.lineno, _end_lineno(node), new))
        converted += 1
    if relocate:
        last_import_end = max(_end_lineno(node) for node in tree.body if isinstance(node, ast.Import | ast.ImportFrom))
        block = _emit_cyclic_block(cyclic_in_order, aliases)
        # Pure insertion AFTER the last import line (start = end + 1), never a
        # replacement of it: the import line itself may carry its own
        # replacement (dropping RootModel), and two edits to one line range
        # silently clobber each other.
        replacements.append((last_import_end + 1, last_import_end, "\n" + block))

    # Import fixes, on the same parsed tree: drop RootModel from the pydantic
    # import, add TypeAlias / TypeAliasType imports where the conversions need
    # them. ruff's import sorting normalizes placement afterwards.
    need_type_alias = converted > len(cyclic)
    need_type_alias_type = bool(cyclic)
    typing_handled = False
    for node in tree.body:
        if not isinstance(node, ast.ImportFrom):
            continue
        if node.module == "pydantic":
            names = [alias for alias in node.names if alias.name != "RootModel"]
            text = ast.unparse(ast.ImportFrom(module="pydantic", names=names, level=0)) + "\n" if names else ""
            replacements.append((node.lineno, _end_lineno(node), text))
        elif node.module == "typing":
            typing_handled = True
            names = list(node.names)
            if need_type_alias and not any(alias.name == "TypeAlias" for alias in names):
                names.append(ast.alias(name="TypeAlias"))
            text = ast.unparse(ast.ImportFrom(module="typing", names=names, level=0)) + "\n"
            if need_type_alias_type:
                text += "from typing_extensions import TypeAliasType\n"
            replacements.append((node.lineno, _end_lineno(node), text))
    if not typing_handled and (need_type_alias or need_type_alias_type):
        extra = "from typing import TypeAlias\n" if need_type_alias else ""
        if need_type_alias_type:
            extra += "from typing_extensions import TypeAliasType\n"
        for node in tree.body:
            if isinstance(node, ast.ImportFrom) and node.module == "__future__":
                replacements.append((node.lineno, _end_lineno(node), lines[node.lineno - 1] + extra))
                break

    for start, end, new in sorted(replacements, reverse=True):
        lines[start - 1 : end] = [new]
    source = "".join(lines)

    # model_rebuild() is only valid on classes; drop calls for converted names.
    for name in [*aliases, "Model"]:
        source = re.sub(rf"^{name}\.model_rebuild\(\)\n", "", source, flags=re.MULTILINE)

    source = _JSDOC_LINK_RE.sub(r"\1", source)

    for old, new_name in rename_map.items():
        source = re.sub(rf"\b{old}\b", new_name, source)

    return PostprocessResult(source=source, converted=converted, recursive=sorted(cyclic))


def assert_alias_blocks_present(source: str, recursive: list[str]) -> None:
    """Assert every recursive alias survived post-processing into the output.

    Guards the relocation edit: a silently dropped alias block would only
    surface much later as a NameError at import time of some consumer.
    """
    for name in recursive:
        if not re.search(rf'^{name} = TypeAliasType\("{name}"', source, flags=re.MULTILINE):
            raise PipelineError(f"recursive alias {name!r} is missing from the post-processed output")


def schema_defs(schema: dict[str, Any]) -> dict[str, Any]:
    """The definitions table of a schema ($defs in 2020-12, definitions in draft-07)."""
    defs = schema.get("$defs") or schema.get("definitions")
    if not defs:
        raise PipelineError("schema has no $defs/definitions table")
    return defs


def build_manifest(schema: dict[str, Any], rename_map: dict[str, str]) -> str:
    """Render the SPEC_DEFS manifest appended to each generated module."""
    names = sorted(rename_map.get(name, name) for name in schema_defs(schema))
    body = "".join(f'    "{name}",\n' for name in names)
    return f"\nSPEC_DEFS: tuple[str, ...] = (\n{body})\n"


def run_ruff(path: Path, *, allow_e501: bool) -> int:
    """ruff check --fix + format with the repo config; return the residual E501 count.

    Oracle mode tolerates residual E501 (per-file-ignored for the generated
    test modules once installed); src mode does not — the docstring-wrap pass
    must leave nothing over the line limit. Any other residual finding aborts
    the pipeline in both modes.
    """
    common = ["uv", "run", "--frozen", "ruff"]
    fix = subprocess.run(
        [*common, "check", "--no-cache", "--fix", "--exit-zero", str(path)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if fix.returncode != 0:
        raise PipelineError(f"ruff check --fix failed:\n{fix.stderr.strip()}")
    if not allow_e501:
        # Strict mode reports after formatting: long code lines are the
        # formatter's job, and only what it cannot wrap should fail the run.
        pre_fmt = subprocess.run(
            [*common, "format", "--no-cache", str(path)], cwd=REPO_ROOT, capture_output=True, text=True
        )
        if pre_fmt.returncode != 0:
            raise PipelineError(f"ruff format failed:\n{pre_fmt.stderr.strip()}")
    report = subprocess.run(
        [*common, "check", "--no-cache", "--output-format", "json", "--exit-zero", str(path)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if report.returncode != 0:
        raise PipelineError(f"ruff check (report) failed:\n{report.stderr.strip()}")
    findings: list[dict[str, Any]] = json.loads(report.stdout)
    residual = [f for f in findings if f.get("code") != "E501"] if allow_e501 else findings
    if residual:
        details = "\n".join(
            f"  {f.get('code')}: {f.get('message')} (line {f.get('location', {}).get('row')})" for f in residual
        )
        raise PipelineError(f"ruff residual findings in {path.name}:\n{details}")
    fmt = subprocess.run([*common, "format", "--no-cache", str(path)], cwd=REPO_ROOT, capture_output=True, text=True)
    if fmt.returncode != 0:
        raise PipelineError(f"ruff format failed:\n{fmt.stderr.strip()}")
    return len(findings) - len(residual)


def import_candidate(path: Path, module: str) -> ModuleType:
    """Import a staged candidate module under a private name."""
    name = f"_candidate_{module}"
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise PipelineError(f"cannot load candidate module from {path}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def audit_candidate(mod: ModuleType, schema: dict[str, Any], entry: Entry, rename_map: dict[str, str]) -> None:
    """Def-name + alias + requiredness audit; raises on any failure."""
    problems: list[str] = []
    for def_name, def_schema in schema_defs(schema).items():
        attr = rename_map.get(def_name, def_name)
        obj = getattr(mod, attr, None)
        if obj is None:
            problems.append(f"def {def_name!r} does not resolve to attribute {attr!r}")
            continue
        if not (isinstance(obj, type) and issubclass(obj, BaseModel)):
            continue  # type aliases / Literal aliases have no fields to audit
        properties: dict[str, Any] = def_schema.get("properties", {})
        required: list[str] = def_schema.get("required", [])
        fields_by_wire_name = {
            (info.serialization_alias or info.alias or field_name): info
            for field_name, info in obj.model_fields.items()
        }
        for prop_name in properties:
            info = fields_by_wire_name.get(prop_name)
            if info is None:
                problems.append(f"{attr}: no field with wire name {prop_name!r}")
                continue
            if info.is_required() != (prop_name in required):
                problems.append(
                    f"{attr}.{prop_name}: requiredness mismatch "
                    f"(model={info.is_required()}, schema={prop_name in required})"
                )
    if problems:
        raise PipelineError(f"{entry.key}: audit failed:\n" + "\n".join(f"  - {p}" for p in problems))


def _annotation_models(annotation: Any) -> list[type[BaseModel]]:
    """Model classes appearing anywhere in an annotation."""
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return [annotation]
    found: list[type[BaseModel]] = []
    for arg in typing.get_args(annotation):
        found.extend(_annotation_models(arg))
    return found


def audit_meta_carriers(mod: ModuleType, entry: Entry) -> None:
    """Assert every `_meta` field is an open mapping: a dict or an extra="allow" model.

    A `_meta` carrier that silently dropped unknown keys would lose vendor
    metadata on revalidation; the per-class extra policy must never close one.
    """
    problems: list[str] = []
    for name in dir(mod):
        obj = getattr(mod, name)
        if not (isinstance(obj, type) and issubclass(obj, BaseModel)):
            continue
        for field_name, info in obj.model_fields.items():
            if (info.serialization_alias or info.alias or field_name) != "_meta":
                continue
            problems.extend(
                f"{name}._meta references {referenced.__name__}, which is not extra='allow'"
                for referenced in _annotation_models(info.annotation)
                if referenced.model_config.get("extra") != "allow"
            )
    if problems:
        raise PipelineError(f"{entry.key}: _meta carrier audit failed:\n" + "\n".join(f"  - {p}" for p in problems))


def import_check(import_path: str) -> None:
    """The official post-install import gate, in a clean subprocess from the repo root."""
    result = subprocess.run(
        ["uv", "run", "--frozen", "python", "-c", f"import {import_path}"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise PipelineError(f"import check failed for {import_path}:\n{result.stderr.strip()}")


def build_candidate(entry: Entry, sha: str, schema_dir: Path | None, generator_version: str) -> tuple[str, Outcome]:
    """Oracle-mode stages 1-6 (through the audit) for one entry; returns (candidate source, outcome)."""
    schema_json_text, ts_text = obtain_schemas(entry, sha, schema_dir)
    schema: dict[str, Any] = json.loads(schema_json_text)
    protocol_version = extract_protocol_version(entry, ts_text)
    entry.protocol_version = protocol_version
    entry.module = module_name_for(protocol_version)
    entry.sha = sha
    rename_map = RENAME_MAP[entry.key]

    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        schema_file = tmp_dir / "schema.json"
        schema_file.write_text(schema_json_text)
        raw_file = tmp_dir / "raw.py"
        warnings = run_generator(schema_file, raw_file, generator_version, "tests.spec_oracles._base.OracleModel")
        processed = postprocess(raw_file.read_text(), rename_map)
    assert_alias_blocks_present(processed.source, processed.recursive)

    header = HEADER_TEMPLATE.format(
        repo=entry.repo,
        sha=sha,
        schema_path=entry.schema_path,
        protocol_version=entry.protocol_version or "n/a",
        generator_version=generator_version,
        key=entry.key,
    )
    # Staged inside the package so ruff applies the repo config with in-repo
    # first-party import classification, and so the audit import resolves
    # `tests.spec_oracles._base` the same way the installed module will.
    staging = ORACLES_DIR / f"_staging_{entry.module}.py"
    try:
        staging.write_text(header + processed.source + build_manifest(schema, rename_map))
        e501_count = run_ruff(staging, allow_e501=True)
        mod = import_candidate(staging, entry.module)
        audit_candidate(mod, schema, entry, rename_map)
        candidate = staging.read_text()
    finally:
        staging.unlink(missing_ok=True)

    outcome = Outcome(
        entry=entry,
        def_count=len(schema_defs(schema)),
        converted_aliases=processed.converted,
        recursive_aliases=processed.recursive,
        generator_warnings=warnings,
        e501_count=e501_count,
    )
    return candidate, outcome


# ---------------------------------------------------------------------------
# src mode: the committed per-version wire-model packages
# ---------------------------------------------------------------------------

SRC_HEADER_TEMPLATE = '''\
"""Internal wire-shape models for protocol {protocol_version}. Not part of the public API.

Initially generated from {schema_path} @ {sha} by
``scripts/update_spec_types.py --src`` (datamodel-code-generator
{generator_version}), then hand-validated against the pinned schema.
Maintained as ordinary source: edits are permitted, but
``tests/types/test_version_model_parity.py`` pins every definition against the
generated spec oracle for this version — a drifting edit fails CI. Prefer
fixing the generator pass and re-scaffolding over hand-patching.

The models are deliberately closed (``extra="ignore"``) even where the schema
declares an object open to extra fields — see ``mcp.types._wire_base`` for the
rationale. The classes kept open are commented in place.
{version_notes}
Models live in this package's ``__init__.py`` so the whole version reads as
one file beside its pinned schema; the package form leaves room for a future
per-family split without import-path churn.
"""
'''

# Appended to the 2026-07-28 package docstring: at that revision the reserved
# `_meta` interiors validate through typed models, so revalidation drops
# vendor extras nested inside those two values (a recorded, deliberate cost —
# a transitive extra="allow" closure would leak superset fields instead).
_DRAFT_INTERIOR_NOTE = """
At this revision the ``clientInfo``/``clientCapabilities`` values inside a
request's ``_meta`` validate through typed models, so vendor extra keys
nested inside those two values do not survive revalidation.
"""

_SRC_BASE_CLASS = "mcp.types._wire_base.WireModel"
_SRC_BASE_NAMES = frozenset({"WireModel", "OpenWireModel"})

# Wire names whose referenced classes stay extra="allow": schema-open
# pass-through interiors whose unknown keys must survive revalidation.
_OPEN_INTERIOR_FIELD_ALIASES = frozenset({"inputSchema", "outputSchema"})
_OPEN_INTERIOR_COMMENT = "    # Stays open: schema keywords beyond the declared properties ride extra fields.\n"
_SUBSCRIPTION_FILTER_COMMENT = "    # Stays open: filter contents are extensible on the wire.\n"

# Content-block definitions carried into packages older than the schema that
# introduces them, so serializing such a block to an older peer passes it
# through instead of refusing. Class text matches the generated form in the
# first defining version, after the value-type downgrade (base64 -> str).
_T5_COMMENT = (
    "# Not in this version's schema ({intro_version} introduced it): the SDK emits\n"
    "# this content block to older peers unchanged rather than refusing. The only\n"
    "# content arms deliberately absent from older packages are the tool blocks\n"
    "# added in 2025-11-25.\n"
)
_AUDIO_CONTENT_TEMPLATE = '''\
class AudioContent(WireModel):
    """Audio provided to or from an LLM."""

    annotations: Annotations | None = None
    """
    Optional annotations for the client.
    """
    data: str
    """
    The base64-encoded audio data.
    """
    mime_type: Annotated[str, Field(alias="mimeType")]
    """
    The MIME type of the audio. Different providers may support different audio types.
    """
    type: Literal["audio"]
'''
_RESOURCE_LINK_TEMPLATE = '''\
class ResourceLink(WireModel):
    """A resource that the server is capable of reading, included in a prompt or tool call result.

    Note: resource links returned by tools are not guaranteed to appear in the results of `resources/list` requests.
    """

    meta: Annotated[dict[str, Any] | None, Field(alias="_meta")] = None
    """
    See [General fields: `_meta`](/specification/2025-06-18/basic/index#meta) for notes on `_meta` usage.
    """
    annotations: Annotations | None = None
    """
    Optional annotations for the client.
    """
    description: str | None = None
    """
    A description of what this resource represents.

    This can be used by clients to improve the LLM's understanding of available resources. It can be thought of like a
    "hint" to the model.
    """
    mime_type: Annotated[str | None, Field(alias="mimeType")] = None
    """
    The MIME type of this resource, if known.
    """
    name: str
    """
    Intended for programmatic or logical use, but used as a display name in past specs or fallback (if title isn't
    present).
    """
    size: int | None = None
    """
    The size of the raw resource content, in bytes (i.e., before base64 encoding or any tokenization), if known.

    This can be used by Hosts to display file sizes and estimate context window usage.
    """
    title: str | None = None
    """
    Intended for UI and end-user contexts — optimized to be human-readable and easily understood,
    even by those unfamiliar with domain-specific terminology.

    If not provided, the name should be used for display (except for Tool,
    where `annotations.title` should be given precedence over using `name`,
    if present).
    """
    type: Literal["resource_link"]
    uri: str
    """
    The URI of this resource.
    """
'''


def downgrade_value_transforms(source: str) -> str:
    """Replace value-transforming pydantic types with plain ``str``.

    URL normalization and base64 re-encoding change bytes on a validate ->
    re-dump round trip; the wire models must reproduce input bytes exactly.
    """
    source = re.sub(r"\b(AnyUrl|FileUrl|Base64Str)\b", "str", source)
    # Drop the now-unused names from the pydantic import (ruff would flag them).
    match = re.search(r"^from pydantic import (.+)$", source, flags=re.MULTILINE)
    if match:
        names = [n.strip() for n in match.group(1).split(",")]
        kept = [n for n in names if n != "str"]
        source = source.replace(match.group(0), f"from pydantic import {', '.join(kept)}")
    return source


def widen_structured_content(source: str) -> str:
    """Widen typed ``structuredContent`` fields to ``Any``.

    The newest schema types the field ``Any``; older schemas say
    ``dict[str, Any]``. The wire models never narrow values an SDK model
    accepts, so a scalar structured result passes through at every version.
    """
    tree = ast.parse(source)
    lines = source.splitlines(keepends=True)
    statements = [
        stmt
        for node in tree.body
        if isinstance(node, ast.ClassDef)
        for stmt in node.body
        if isinstance(stmt, ast.AnnAssign)
        and isinstance(stmt.target, ast.Name)
        and stmt.target.id == "structured_content"
    ]
    for stmt in sorted(statements, key=lambda s: s.lineno, reverse=True):
        start, end = stmt.lineno, _end_lineno(stmt)
        segment = "".join(lines[start - 1 : end])
        lines[start - 1 : end] = [segment.replace("dict[str, Any]", "Any")]
    return "".join(lines)


def _class_field_aliases(node: ast.ClassDef) -> list[tuple[ast.AnnAssign, str, str]]:
    """(statement, field name, wire alias) for every annotated field of a class."""
    out: list[tuple[ast.AnnAssign, str, str]] = []
    for stmt in node.body:
        if not isinstance(stmt, ast.AnnAssign) or not isinstance(stmt.target, ast.Name):
            continue
        annotation_text = ast.unparse(stmt.annotation)
        alias_match = _FIELD_ALIAS_RE.search(annotation_text)
        alias = alias_match.group(1) if alias_match else stmt.target.id
        out.append((stmt, stmt.target.id, alias))
    return out


def flatten_inheritance(source: str) -> tuple[str, list[str]]:
    """Flatten classes that subclass other generated classes.

    The generator emits subclassing when one definition narrows another (the
    named-error family, the 2025-11-25 task results); pyright's
    dataclass-transform rules reject the narrowed overrides, and the committed
    packages carry no suppressions. Flattening re-declares the inherited
    fields directly: base fields in base order, overrides in place, own fields
    appended.
    """
    tree = ast.parse(source)
    lines = source.splitlines(keepends=True)
    classes: dict[str, ast.ClassDef] = {n.name: n for n in tree.body if isinstance(n, ast.ClassDef)}

    def field_segments(node: ast.ClassDef) -> list[tuple[str, str]]:
        """(field name, source text incl. trailing docstring) per field."""
        segments: list[tuple[str, str]] = []
        body = list(node.body)
        for index, stmt in enumerate(body):
            if not isinstance(stmt, ast.AnnAssign) or not isinstance(stmt.target, ast.Name):
                continue
            end = _end_lineno(stmt)
            if index + 1 < len(body):
                nxt = body[index + 1]
                if isinstance(nxt, ast.Expr) and isinstance(nxt.value, ast.Constant):
                    if isinstance(nxt.value.value, str):
                        end = _end_lineno(nxt)
            segments.append((stmt.target.id, "".join(lines[stmt.lineno - 1 : end])))
        return segments

    resolved: dict[str, list[tuple[str, str]]] = {}

    def resolve(name: str) -> list[tuple[str, str]]:
        if name in resolved:
            return resolved[name]
        node = classes[name]
        base_names = [b.id for b in node.bases if isinstance(b, ast.Name) and b.id in classes]
        merged: list[tuple[str, str]] = []
        for base in base_names:
            for field_name, text in resolve(base):
                if field_name not in {n for n, _ in merged}:
                    merged.append((field_name, text))
        for field_name, text in field_segments(node):
            existing = [i for i, (n, _) in enumerate(merged) if n == field_name]
            if existing:
                merged[existing[0]] = (field_name, text)
            else:
                merged.append((field_name, text))
        resolved[name] = merged
        return merged

    flattened: list[str] = []
    replacements: list[tuple[int, int, str]] = []
    for name, node in classes.items():
        generated_bases = [b.id for b in node.bases if isinstance(b, ast.Name) and b.id in classes]
        if not generated_bases:
            continue
        flattened.append(name)
        parts: list[str] = [f"class {name}(WireModel):\n"]
        if ast.get_docstring(node) is not None:
            stmt = node.body[0]
            parts.append("".join(lines[stmt.lineno - 1 : _end_lineno(stmt)]))
        parts.extend(
            "".join(lines[stmt.lineno - 1 : _end_lineno(stmt)])
            for stmt in node.body
            if isinstance(stmt, ast.Assign)
            and any(isinstance(t, ast.Name) and t.id == "model_config" for t in stmt.targets)
        )
        parts.extend(text for _, text in resolve(name))
        replacements.append((node.lineno, _end_lineno(node), "".join(parts)))

    for start, end, new in sorted(replacements, reverse=True):
        lines[start - 1 : end] = [new]
    return "".join(lines), sorted(flattened)


def rebase_meta_carriers(source: str) -> tuple[str, list[str]]:
    """Rebase classes referenced from ``_meta`` fields onto ``OpenWireModel``.

    Unknown ``_meta`` keys must survive a validate -> re-dump round trip at
    every version, so their carrier classes keep ``extra="allow"`` through the
    open base rather than a per-class config.
    """
    tree = ast.parse(source)
    classes: dict[str, ast.ClassDef] = {n.name: n for n in tree.body if isinstance(n, ast.ClassDef)}
    carriers: set[str] = set()
    for node in classes.values():
        for stmt, _, alias in _class_field_aliases(node):
            if alias != "_meta":
                continue
            annotation_text = ast.unparse(stmt.annotation)
            carriers.update(name for name in classes if re.search(rf"\b{name}\b", annotation_text))
    for name in sorted(carriers):
        source = re.sub(
            rf"^class {name}\(WireModel\):$",
            f"class {name}(OpenWireModel):",
            source,
            flags=re.MULTILINE,
        )
    return source, sorted(carriers)


def apply_extra_policy(source: str, carriers: list[str]) -> tuple[str, list[str]]:
    """Force ``extra="ignore"`` everywhere except the enumerated open classes.

    The generator emits per-class ``extra="allow"`` wherever the schema has an
    index signature. Open models would retain fields the target version never
    defined, so a version-mismatched field would never register as a loss on
    revalidation; closing them is what makes those fields detectable. The
    classes that stay open are exactly: ``_meta`` carriers (via the open
    base), the tool input/output schema interiors, and the subscription
    filter.
    """
    tree = ast.parse(source)
    lines = source.splitlines(keepends=True)
    classes: dict[str, ast.ClassDef] = {n.name: n for n in tree.body if isinstance(n, ast.ClassDef)}

    keep_allow: set[str] = set()
    for node in classes.values():
        for stmt, _, alias in _class_field_aliases(node):
            if alias in _OPEN_INTERIOR_FIELD_ALIASES:
                annotation_text = ast.unparse(stmt.annotation)
                keep_allow.update(name for name in classes if re.search(rf"\b{name}\b", annotation_text))
    if "SubscriptionFilter" in classes:
        keep_allow.add("SubscriptionFilter")

    replacements: list[tuple[int, int, str]] = []
    for name, node in classes.items():
        config_stmt = next(
            (
                stmt
                for stmt in node.body
                if isinstance(stmt, ast.Assign)
                and any(isinstance(t, ast.Name) and t.id == "model_config" for t in stmt.targets)
            ),
            None,
        )
        if config_stmt is None:
            continue
        value = config_stmt.value
        is_plain_allow = (
            isinstance(value, ast.Call)
            and isinstance(value.func, ast.Name)
            and value.func.id == "ConfigDict"
            and len(value.keywords) == 1
            and value.keywords[0].arg == "extra"
            and isinstance(value.keywords[0].value, ast.Constant)
            and value.keywords[0].value.value == "allow"
        )
        if not is_plain_allow:
            raise PipelineError(f"unexpected model_config on {name}: {ast.unparse(config_stmt)}")
        if name in keep_allow and name not in carriers:
            comment = _SUBSCRIPTION_FILTER_COMMENT if name == "SubscriptionFilter" else _OPEN_INTERIOR_COMMENT
            replacements.append((config_stmt.lineno, config_stmt.lineno - 1, comment))
            continue
        remaining = [stmt for stmt in node.body if stmt is not config_stmt]
        new = "" if remaining else "    pass\n"
        replacements.append((config_stmt.lineno, _end_lineno(config_stmt), new))

    for start, end, new in sorted(replacements, reverse=True):
        lines[start - 1 : end] = [new]
    return "".join(lines), sorted(keep_allow)


def deterministic_synthetic_names(source: str) -> tuple[str, dict[str, str], list[str]]:
    """Rename counter-based synthetic classes after their single owner.

    The generator names inline params/meta objects ``Params``/``Params1``/...
    in discovery order, so an inserted definition renumbers every later one
    and pollutes cross-version diffs. A synthetic class referenced by exactly
    one field of one owner is renamed ``<Owner>Params``/``<Owner>Meta``;
    shared or colliding names keep their generated form.
    """
    tree = ast.parse(source)
    classes: dict[str, ast.ClassDef] = {n.name: n for n in tree.body if isinstance(n, ast.ClassDef)}
    synthetic = {name for name in classes if re.fullmatch(r"(?:Params|Meta)\d*", name)}
    references: dict[str, list[tuple[str, str]]] = {name: [] for name in synthetic}
    for node in classes.values():
        for stmt, field_name, _ in _class_field_aliases(node):
            annotation_text = ast.unparse(stmt.annotation)
            for name in synthetic:
                if re.search(rf"\b{name}\b", annotation_text):
                    references[name].append((node.name, field_name))

    renames: dict[str, str] = {}
    skipped: list[str] = []
    taken = set(classes)
    for name in sorted(synthetic):
        refs = references[name]
        if len(refs) != 1:
            skipped.append(f"{name} ({len(refs)} references)")
            continue
        owner, field_name = refs[0]
        suffix = {"params": "Params", "meta": "Meta"}.get(field_name)
        if suffix is None:
            skipped.append(f"{name} (referenced from field {field_name!r})")
            continue
        target = f"{owner}{suffix}"
        if target in taken:
            skipped.append(f"{name} (target {target} already exists)")
            continue
        renames[name] = target
        taken.add(target)

    if renames:
        pattern = re.compile(r"\b(" + "|".join(sorted(renames, key=len, reverse=True)) + r")\b")
        source = pattern.sub(lambda m: renames[m.group(1)], source)
    return source, renames, skipped


def add_early_content_arms(source: str, protocol_version: str) -> tuple[str, list[str]]:
    """Carry newer content-block definitions into the older packages.

    ``audio`` (2025-03-26) and ``resource_link`` (2025-06-18) content emitted
    to an older peer passes through unchanged rather than being refused, so
    the older packages carry the definitions and union arms early.
    """
    added: list[str] = []
    if protocol_version == "2024-11-05":
        source = _splice_class_after(
            source,
            "ImageContent",
            _T5_COMMENT.format(intro_version="2025-03-26") + _AUDIO_CONTENT_TEMPLATE,
        )
        source = _add_union_arm(source, "TextContent | ImageContent", "TextContent | ImageContent | AudioContent")
        added.append("AudioContent")
    if protocol_version in ("2024-11-05", "2025-03-26"):
        source = _splice_class_after(
            source,
            "EmbeddedResource",
            _T5_COMMENT.format(intro_version="2025-06-18") + _RESOURCE_LINK_TEMPLATE,
        )
        source = _add_union_arm(source, "| EmbeddedResource", "| ResourceLink | EmbeddedResource")
        added.append("ResourceLink")
    return source, added


def _splice_class_after(source: str, anchor_class: str, class_text: str) -> str:
    """Insert a class definition immediately after ``anchor_class``."""
    tree = ast.parse(source)
    anchor = next((n for n in tree.body if isinstance(n, ast.ClassDef) and n.name == anchor_class), None)
    if anchor is None:
        raise PipelineError(f"cannot splice after {anchor_class!r}: class not found")
    lines = source.splitlines(keepends=True)
    end = _end_lineno(anchor)
    lines[end:end] = ["\n\n" + class_text]
    return "".join(lines)


def _add_union_arm(source: str, old: str, new: str) -> str:
    """Widen every content union matching ``old`` and comment the change."""
    note = "    # Carries arms beyond this version's schema; see the class comments above.\n"
    out_lines: list[str] = []
    for line in source.splitlines(keepends=True):
        if old in line and not line.lstrip().startswith(("#", "class ")):
            if not out_lines or out_lines[-1] != note:
                out_lines.append(note)
            line = line.replace(old, new)
        out_lines.append(line)
    return "".join(out_lines)


def _join_class_docstring_summaries(source: str) -> str:
    """Move each class docstring summary onto the opening quote line.

    This is the fix the D212 lint rule would apply later; doing it first
    keeps the long-line wrapping below in charge of the resulting line
    length. Field annotation strings are not docstrings and stay untouched.
    """
    tree = ast.parse(source)
    lines = source.splitlines(keepends=True)
    for node in tree.body:
        if not isinstance(node, ast.ClassDef) or ast.get_docstring(node) is None:
            continue
        stmt = node.body[0]
        first = lines[stmt.lineno - 1]
        if first.strip() != '"""' or _end_lineno(stmt) == stmt.lineno:
            continue
        summary = lines[stmt.lineno].strip()
        single_content = _end_lineno(stmt) == stmt.lineno + 2
        indent = first[: len(first) - len(first.lstrip())]
        if single_content:
            # The formatter collapses a one-line docstring body onto a single
            # line; emit that form directly when it fits, otherwise pre-wrap
            # the summary so the body stays multi-line.
            if len(indent) + len(summary) + 6 <= 120:
                lines[stmt.lineno - 1] = f'{indent}"""{summary}"""\n'
                lines[stmt.lineno] = ""
                lines[stmt.lineno + 1] = ""
            else:
                # Width leaves room for the closing quotes in case the wrap
                # still fits on one line and the formatter collapses it.
                wrapped = textwrap.wrap(
                    summary,
                    width=117,
                    initial_indent=indent + '"""',
                    subsequent_indent=indent,
                    break_long_words=False,
                    break_on_hyphens=False,
                )
                lines[stmt.lineno - 1] = "".join(part + "\n" for part in wrapped)
                lines[stmt.lineno] = ""
            continue
        lines[stmt.lineno - 1] = first.rstrip("\n") + summary + "\n"
        lines[stmt.lineno] = ""
    return "".join(lines)


def wrap_docstrings(source: str) -> str:
    """Wrap docstring lines to the repo line length.

    The schema prose stays (the file should read as the spec), but committed
    src modules carry no per-file lint exemptions, so long lines wrap. Both
    body lines and opening-quote summary lines are wrapped; anything this
    pass cannot handle fails the strict ruff stage.
    """
    source = _join_class_docstring_summaries(source)
    out: list[str] = []
    in_docstring = False
    for line in source.splitlines(keepends=True):
        quotes = line.count('"""')
        long = len(line.rstrip("\n")) > 120
        indent = line[: len(line) - len(line.lstrip())]
        if not in_docstring:
            if quotes == 1:
                in_docstring = True
                if long:
                    out.extend(
                        part + "\n"
                        for part in textwrap.wrap(
                            line.strip().removeprefix('"""'),
                            width=120,
                            initial_indent=indent + '"""',
                            subsequent_indent=indent,
                            break_long_words=False,
                            break_on_hyphens=False,
                        )
                    )
                    continue
            out.append(line)
            continue
        if quotes:
            in_docstring = False
            out.append(line)
            continue
        if not long:
            out.append(line)
            continue
        out.extend(
            part + "\n"
            for part in textwrap.wrap(
                line.strip(),
                width=120,
                initial_indent=indent,
                subsequent_indent=indent,
                break_long_words=False,
                break_on_hyphens=False,
            )
        )
    return "".join(out)


def assert_only_wire_bases(source: str) -> None:
    """Assert every class in the emitted package sits on one of the two bases."""
    tree = ast.parse(source)
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        base_names = [ast.unparse(b) for b in node.bases]
        if base_names not in (["WireModel"], ["OpenWireModel"]):
            raise PipelineError(f"class {node.name} has unexpected bases {base_names} after the src passes")


def build_src_candidate(entry: Entry, sha: str, schema_dir: Path | None, generator_version: str) -> tuple[str, Outcome]:
    """src-mode pipeline for one entry; returns (candidate source, outcome)."""
    if importlib.util.find_spec("mcp.types._wire_base") is None:
        raise PipelineError("src mode requires src/mcp/types/_wire_base.py (WireModel/OpenWireModel) to exist")
    schema_json_text, ts_text = obtain_schemas(entry, sha, schema_dir)
    schema: dict[str, Any] = json.loads(schema_json_text)
    protocol_version = extract_protocol_version(entry, ts_text)
    entry.protocol_version = protocol_version
    entry.module = module_name_for(protocol_version)
    entry.sha = sha
    rename_map = RENAME_MAP[entry.key]

    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        schema_file = tmp_dir / "schema.json"
        schema_file.write_text(schema_json_text)
        raw_file = tmp_dir / "raw.py"
        warnings = run_generator(schema_file, raw_file, generator_version, _SRC_BASE_CLASS)
        processed = postprocess(raw_file.read_text(), rename_map)
    assert_alias_blocks_present(processed.source, processed.recursive)

    notes: list[str] = []
    source = downgrade_value_transforms(processed.source)
    source = widen_structured_content(source)
    source, flattened = flatten_inheritance(source)
    if flattened:
        notes.append(f"flattened: {', '.join(flattened)}")
    source, carriers = rebase_meta_carriers(source)
    if carriers:
        notes.append(f"meta carriers on OpenWireModel: {', '.join(carriers)}")
        source = source.replace(
            "from mcp.types._wire_base import WireModel",
            "from mcp.types._wire_base import OpenWireModel, WireModel",
        )
    source, keep_allow = apply_extra_policy(source, carriers)
    if keep_allow:
        notes.append(f"extra=allow kept: {', '.join(sorted(set(keep_allow) - set(carriers)))}")
    source, renames, skipped = deterministic_synthetic_names(source)
    notes.append(f"synthetic renames: {len(renames)}, kept generated names: {len(skipped)}")
    if skipped:
        notes.append(f"kept: {'; '.join(skipped)}")
    source, t5 = add_early_content_arms(source, protocol_version)
    if t5:
        notes.append(f"early content arms: {', '.join(t5)}")
    source = wrap_docstrings(source)

    header = SRC_HEADER_TEMPLATE.format(
        protocol_version=protocol_version,
        schema_path=entry.schema_path,
        sha=sha,
        generator_version=generator_version,
        version_notes=_DRAFT_INTERIOR_NOTE if protocol_version == "2026-07-28" else "",
    )
    staging = SRC_TYPES_DIR / f"_staging_{entry.module}.py"
    try:
        staging.write_text(header + source)
        run_ruff(staging, allow_e501=False)
        candidate = staging.read_text()
        assert_only_wire_bases(candidate)
        mod = import_candidate(staging, entry.module)
        audit_candidate(mod, schema, entry, rename_map)
        audit_meta_carriers(mod, entry)
    finally:
        staging.unlink(missing_ok=True)

    outcome = Outcome(
        entry=entry,
        def_count=len(schema_defs(schema)),
        converted_aliases=processed.converted,
        recursive_aliases=processed.recursive,
        generator_warnings=warnings,
        e501_count=0,
        src_notes=notes,
    )
    return candidate, outcome


def write_back_pinned(pinned: dict[str, Any], entries: list[Entry]) -> None:
    """Rewrite the derived fields (sha, protocol_version, module) into PINNED.json."""
    by_key = {e.key: e for e in entries}
    for table in (pinned["versions"], pinned["extensions"]):
        for key, data in table.items():
            if key in by_key:
                entry = by_key[key]
                data["sha"] = entry.sha
                data["protocol_version"] = entry.protocol_version
                data["module"] = entry.module
    PINNED_PATH.write_text(json.dumps(pinned, indent=2) + "\n")


def delete_orphans(pinned: dict[str, Any]) -> list[str]:
    """Delete generated oracle modules that no PINNED.json entry produces any more."""
    known = {data["module"] for data in pinned["versions"].values()}
    known |= {data["module"] for data in pinned["extensions"].values()}
    deleted: list[str] = []
    for path in sorted(ORACLES_DIR.glob("*.py")):
        if path.stem.startswith(("_", "test_")) or path.name == "__init__.py":
            continue
        if path.stem not in known:
            path.unlink()
            deleted.append(path.name)
    return deleted


def summarize(outcomes: list[Outcome], *, src: bool) -> None:
    """Print the per-entry generation summary."""
    for o in outcomes:
        target = f"src/mcp/types/{o.entry.module}/__init__.py" if src else f"tests/spec_oracles/{o.entry.module}.py"
        print(
            f"{o.entry.key}: {o.action} -> {target} "
            f"(defs={o.def_count}, alias_conversions={o.converted_aliases}, "
            f"recursive={o.recursive_aliases or 'none'}, residual_E501={o.e501_count})"
        )
        for note in o.src_notes:
            print(f"  {note}")
        for warning in o.generator_warnings:
            print(f"  generator warning: {warning}")


def main(argv: list[str] | None = None) -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("keys", nargs="*", help="PINNED.json entries to regenerate (default: all non-frozen)")
    parser.add_argument("--all", action="store_true", help="select every entry")
    parser.add_argument("--src", action="store_true", help="emit src/mcp/types/v<version>/ packages")
    parser.add_argument("--sha", help="override the pinned SHA (single KEY only); written back on success")
    parser.add_argument("--schema-dir", type=Path, help="read schemas from this directory instead of fetching")
    parser.add_argument("--check", action="store_true", help="diff regenerated output against committed modules")
    parser.add_argument("--force", action="store_true", help="regenerate frozen entries / overwrite src packages")
    args = parser.parse_args(argv)

    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))

    pinned = load_pinned()
    entries = iter_entries(pinned)
    valid_keys = [e.key for e in entries]
    if args.all:
        selected = entries
    elif args.keys:
        unknown = [k for k in args.keys if k not in valid_keys]
        if unknown:
            parser.error(f"unknown KEY(s) {unknown}; valid: {valid_keys}")
        selected = [e for e in entries if e.key in args.keys]
    elif args.src:
        selected = entries
    else:
        selected = [e for e in entries if not e.frozen]
    if args.sha and (len(selected) != 1 or args.src):
        parser.error("--sha requires exactly one KEY in oracle mode")

    generator_version: str = pinned["generator"]["version"]
    outcomes: list[Outcome] = []
    drifted: list[str] = []
    regenerated: list[Entry] = []
    for entry in selected:
        if args.src:
            candidate, outcome = build_src_candidate(entry, entry.sha, args.schema_dir, generator_version)
            target = SRC_TYPES_DIR / entry.module / "__init__.py"
            if args.check:
                if target.is_file() and target.read_text() == candidate:
                    outcome.action = "checked"
                else:
                    outcome.action = "drifted"
                    drifted.append(entry.module)
            elif target.is_file() and not args.force:
                outcome.action = "exists (scaffold refused; pass --force to overwrite)"
            else:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(candidate)
                outcome.action = "installed"
                import_check(f"mcp.types.{entry.module}")
            outcomes.append(outcome)
            continue
        target = ORACLES_DIR / f"{entry.module}.py"
        if entry.frozen and target.is_file() and not (args.force or args.check):
            print(f"{entry.key}: frozen (released schemas are generate-once); use --force to regenerate")
            continue
        candidate, outcome = build_candidate(entry, args.sha or entry.sha, args.schema_dir, generator_version)
        target = ORACLES_DIR / f"{entry.module}.py"  # module may have been re-derived
        if args.check:
            if target.is_file() and target.read_text() == candidate:
                outcome.action = "checked"
            else:
                outcome.action = "drifted"
                drifted.append(entry.module)
        else:
            if target.is_file() and target.read_text() == candidate:
                outcome.action = "unchanged"
            else:
                target.write_text(candidate)
                outcome.action = "installed"
            import_check(f"tests.spec_oracles.{entry.module}")
            regenerated.append(entry)
        outcomes.append(outcome)

    if regenerated and not args.check:
        write_back_pinned(pinned, regenerated)
        for name in delete_orphans(pinned):
            print(f"deleted orphaned module: {name}")

    summarize(outcomes, src=args.src)
    if drifted:
        print(f"DRIFT: {drifted} differ from committed output", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
