"""A language's `nav.yml`: its translated navigation labels and their staleness.

The sidebar labels — section titles and the labels of explicit `Label: page`
entries — live in `mkdocs.yml` and are English source like the pages. Each
language carries one generated map from English label to its rendering, made
by a single model call over the whole label list, plus a state block that
fingerprints the label list and the same three prompt inputs a page records.
A label added to the nav, or an instructions or glossary edit, marks the map
outdated; the language build swaps the renderings into its sidebar and leaves
any label the map does not cover in English.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Literal, cast

import yaml

from i18n.config import ConfigError
from i18n.files import write_text_atomically
from i18n.pages import sha256

SCHEMA_VERSION = 1
NavStatusKind = Literal["missing", "outdated", "current"]

_TOP_KEYS = {"version", "labels", "state"}
# A note for anyone opening the generated file; corrections belong in the
# language's instructions or glossary, and the loader ignores comments.
_HEADER = "# Generated by scripts/docs/i18n (`translate --nav`). Never edit by hand; see i18n/README.md.\n"


@dataclass(frozen=True)
class NavFingerprint:
    """Everything a translated nav depends on; equality means the map is still current."""

    labels_hash: str
    general_prompt_hash: str
    instructions_hash: str
    glossary_hash: str


@dataclass(frozen=True)
class NavState:
    """What a language's nav labels were generated from."""

    labels_hash: str
    general_prompt_hash: str
    instructions_hash: str
    glossary_hash: str
    model: str
    translated_at: str

    @property
    def fingerprint(self) -> NavFingerprint:
        return NavFingerprint(
            labels_hash=self.labels_hash,
            general_prompt_hash=self.general_prompt_hash,
            instructions_hash=self.instructions_hash,
            glossary_hash=self.glossary_hash,
        )


@dataclass(frozen=True)
class NavTranslation:
    """The translated labels (English label -> rendering, in nav order) and their state."""

    labels: dict[str, str]
    state: NavState


@dataclass(frozen=True)
class NavStatus:
    """The classification of one language's nav map."""

    status: NavStatusKind
    reasons: tuple[str, ...] = field(default_factory=tuple)


_STATE_FIELDS = tuple(NavState.__dataclass_fields__)


def labels_hash(labels: Sequence[str]) -> str:
    """The hash of the ordered, de-duplicated English label list."""
    return sha256("\n".join(labels))


def load_nav(path: Path) -> NavTranslation | None:
    """Read a nav map; a missing file means the language has none yet.

    Raises:
        ConfigError: The file exists but is unreadable or off-schema.
    """
    if not path.is_file():
        return None
    try:
        raw: object = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError) as exc:
        raise ConfigError(f"{path}: cannot read nav map: {exc}") from exc
    document = cast("dict[str, Any]", raw) if isinstance(raw, dict) else {}
    if unknown := sorted(set(document) - _TOP_KEYS):
        raise ConfigError(f"{path}: unknown keys {unknown}")
    if document.get("version") != SCHEMA_VERSION:
        raise ConfigError(f"{path}: not a version {SCHEMA_VERSION} nav map")
    labels = document.get("labels")
    if not isinstance(labels, dict) or not all(
        isinstance(label, str) and isinstance(rendering, str)
        for label, rendering in cast("dict[object, object]", labels).items()
    ):
        raise ConfigError(f"{path}: labels must map English label strings to rendering strings")
    return NavTranslation(labels=dict(cast("dict[str, str]", labels)), state=_state(path, document.get("state")))


def _state(path: Path, record: object) -> NavState:
    """The `state` block, validated against the `NavState` fields."""
    if not isinstance(record, dict) or set(cast("dict[str, Any]", record)) != set(_STATE_FIELDS):
        raise ConfigError(f"{path}: state block is off-schema (keys must be {list(_STATE_FIELDS)})")
    fields = cast("dict[str, Any]", record)
    if not all(isinstance(value, str) for value in fields.values()):
        raise ConfigError(f"{path}: state block values must be strings")
    values = cast("dict[str, str]", fields)
    return NavState(
        labels_hash=values["labels_hash"],
        general_prompt_hash=values["general_prompt_hash"],
        instructions_hash=values["instructions_hash"],
        glossary_hash=values["glossary_hash"],
        model=values["model"],
        translated_at=values["translated_at"],
    )


def save_nav(path: Path, nav: NavTranslation) -> None:
    """Write the nav map, labels in nav order, so its diffs stay reviewable."""
    document = {"version": SCHEMA_VERSION, "labels": dict(nav.labels), "state": asdict(nav.state)}
    body = yaml.safe_dump(document, sort_keys=False, allow_unicode=True, width=1000)
    write_text_atomically(path, _HEADER + body)


def classify_nav(labels: Sequence[str], current: NavFingerprint, nav: NavTranslation | None) -> NavStatus:
    """Classify a language's nav map against today's label list and prompt inputs.

    `current` is the fingerprint a map made right now would record; a nav
    without any translatable labels owes nothing and is trivially current.
    """
    if not labels:
        return NavStatus("current")
    if nav is None:
        return NavStatus("missing")
    if nav.state.fingerprint == current:
        return NavStatus("current")
    return NavStatus("outdated", _reasons(nav.state.fingerprint, current))


def _reasons(recorded: NavFingerprint, current: NavFingerprint) -> tuple[str, ...]:
    """Why a nav map is outdated, most specific cause first."""
    reasons: list[str] = []
    if recorded.labels_hash != current.labels_hash:
        reasons.append("nav labels changed")
    if recorded.general_prompt_hash != current.general_prompt_hash:
        reasons.append("general prompt changed")
    if recorded.instructions_hash != current.instructions_hash:
        reasons.append("language instructions changed")
    if recorded.glossary_hash != current.glossary_hash:
        reasons.append("glossary changed")
    return tuple(reasons)
