name: CI

on:
  push:
    branches: ["main", "v1.x"]
    tags: ["v*.*.*"]
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    uses: ./.github/workflows/shared.yml

  all-green:
    if: always()
    needs: [checks]
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # v1.3.0
        with:
          jobs: ${{ toJSON(needs) }}
